### ISSUE TITLE
Cannot get this to run, at all.

### ISSUE THREAD

**Issue by SmurfDaddy69** [WagicProject/wagic#1028]
I've tried this on both a Windows 10 PC and a OG Oled PS Vita. Loading this in Adrenaline, I've consistently failed to get past the loading sets screen, as it proceeds to freeze and crash on seemingly random sets, giving me the error code C1-2858-3, a generic error code for PSP and PS1 titles on the vita with many different solutions, none relevant to my case.. At first it was the set Rise of Eldrazi, then Revised Edition once I deleted the music files. This was before downloading card art, which now places the crashes at the Magic 2012 set. I've been at this for hours, redownloading and transferring between PC and Vita to no avail. I've tried low res image sets, thinking it was a memory or performance issue that was causing the crash, and the lack of information on this has left me dumbfounded. I'm using the most recent version from the Wololo thread posted in a reply to an earlier error comment.

On the PC side, the program fails to even start. I get no error logs, no prompts to install any missing software. Nothing. The process doesn't even show in task manager, so the thing just isn't running at all.

Am I missing something here? On the Vita side, I have the Res and User folders under the game folder which is under PSP, and both the Eboots are where they should be. Am I missing some obscure thing here, or is the game just not loading past the sets normal?

Any help would be appreciated.

**Comment by SmurfDaddy69** [comment]
I've tried compiling it for PSP as well, also to no avail. I followed the steps on the Wiki but upon typing make clean and make for the projects/mtg directory, I get an error that makefile.psp has been deleted, it can't find the directory specified, and links to a file called deckview.d in a folder called deps, which I cannot find on my PC at all. I haven't tried compiling for Windows but I'm just gonna assume it's the same as PSP, ergo it won't work and I shouldn't even bother.

Any information regarding this, hell any help regarding this, would be much appreciated. I saw a previous issue that referenced this that never got a response and the user wound up closing it. Maybe I'm going about this all wrong or something.

**Comment by Darthagnon** [comment]
I've been playing Wagic since 2013-14. I remember hearing around the forums that it had memory leak issues, due to bad cleanup after loading resources (e.g. card art, music). Versions up to v0.19 combined a lot of image resources (e.g. battlefield textures, etc.) into single spritesheets, to save memory. For v0.20, the maintainers decided to split up the spritesheets, into more logical image divisions. Initial complaints that the new version wouldn't even boot on the PSP were addressed with "it's legacy hardware, you shouldn't really expect it to run on it". I don't know if anything's changed since then, but it's likely that the PSP version is still broken (don't know about the Windows version). 

The latest versions to run on the PSP were 0.19 franken-builds by wololo.net/forum members. The latest version I ran on PC was tacoghandi's build from back in the day (based off v0.19)

**Comment by rickteuthof** [comment]
Same here, kept trying to run it on my PSP3004, keeps crashing while loading the sets. Tried an official memory stick and still got the same result. I'm a bit bummed out because i was excited for playing this.

**Comment by SmurfDaddy69** [comment]
I completely forgot to post a reply to this, since I did later figure out how to fix my issue. While running this on Windows and PPSSPP is still impossible for me, I did get it working on Vita.

I dunno how to enable this on original PSPs but Wagic uses 64mb of RAM and will crash otherwise. Found that in a Wololo thread by pure chance. For Adrenaline I just used the recovery menu to change the amount of RAM the CFW uses, but I'm guessing Wagic probably won't work on older PSPs without the proper amount of RAM.

Hope this helped and I sure am glad I stumbled on this because literally no one talks about this shit and it was pure luck I discovered a post about it.

**Comment by rickteuthof** [comment]
@SmurfDaddy69 Your post actually did help! I looked into the PSP pro recovery menu, and in the "Advanced" section, there's an option "Force High Memory Layout". When enabled, wagic won't crash anymore on an original PSP 3004! I hope this helps anyone with the same problem.

**Comment by Vitty85** [comment]
You can enable specific setting for games in Adrenaline, use Adrenaline Bubbles so you can set Extended RAM for WTH and normal RAM for other games.

**Comment by Darthagnon** [comment]
Enabling High Memory Layout allowed v0.22.2 to actually load on my PSP 3003. All was going well, but after playing 2 matches (no artwork installed), and unlocking False God mode, I tried to start it, and pressed for more info on the Premade G/R deck, and it had a classic Wagic crash: freeze-up, MS light flashing non-stop, music still playing. So, still not sure if this is playable. The new Exile/Graveyard/Deck icons are nice, though :)

**Comment by Vitty85** [comment]
On PSVita with high memory profile the crash are not reproducing, I guess on PSP there could be some RAM issue with the new version because of the large amount of included cards and sets.
