### ISSUE TITLE
Version 0.22.2 don't run in PSP

### ISSUE THREAD

**Issue by VenomJack0212** [WagicProject/wagic#1031]
I've tried run in my PSP software version 6.60 Pro-C. The Wagic open but don't load the primitives and turn off the PSP.

The version 0.18.6 work normally, I don't tried with other above version.

**Comment by Vitty85** [comment]
I'm sorry but i guess the PSP does not have enough RAM to run the new version, as far i know, the last version is compatible with PSP emulator on PSVita (Adrenaline) configured with High Memory Profile (64Mb of RAM) and 333Mhz CPU speed.
