### ISSUE TITLE
please correct some card effects

### ISSUE THREAD

**Issue by luisguerin** [WagicProject/wagic#1035]
-cards with rebound arent working properly, i know i asked this last time, but the correction is not working properly, intead of banishhing the instant spell and being able to cast it again in the unkeep of my next turn, the instant card is going to the graveyard and the creature spell that i target is going to exile, i am losing the creature and i cant cast the spell again in next turn unkeep.
-another problem is cards with the mentor ability, when they attack we should be able to put a +1/+1 counter on a creature a control with less power than the creature with mentor, the problem is, the game is counting the original power of the creature with mentor and comparing with the current power of my other creatures to check if its possible to put the counter, so when the power of the creature with mentor is increased by any means the effect still counts only its original attack, please correct this to check the current attack of the creatures
-if possible, the options in "ask about" on the shop or deck building menus could be updated, for example some abilities arent there to filter, like mentor or prowess

**Comment by Vitty85** [comment]
Hi,

1) Just to be sure, can you tell me which card with rebound are you trying? So i can test if next fix will be effective.

2) I will take a look if it's possible to correct this issue in next release.

3) Sorry but Mentor and Prowess are not real abilities in Wagic, they are Macros, so at the moment i cannot alter the menu filters in order to find them.

Let me know.

**Comment by luisguerin** [comment]
About menus, its not a real problem, but mentor hás that problem about
compare the power based on the original power of the creature with mentor
instead of its current power.
The cards with rebound i tested this time were
Artful maneuver
Center soul
Emerge unscathed
Ojutaisempre's breath
Virulent swipe
Distortion strike
All of this worked the same, and im pretty sure all rebound cards will work
like this
The creature i target for the effect got exiled (forever) and the instant
spell gone to graveyard instead of exile, and in my next unkeep nothing, i
cant recast (from grave, the Card isnt exiled anyway, and the creature
doesnot return)

And a Card in particular that is not working is containment menbrane its
surge effect work normally but the Card doea nothing, the creature
enchanted is untaping as normal.



Em dom, 26 de jul de 2020 09:58, Vittorio Alfieri <notifications@github.com>
escreveu:

**Comment by Vitty85** [comment]
Hi,

I have some ideas for possible solution on Mentor and Rebound, can you make some test on these new cards to see if it's ok?

Mentor:
[card]
name=Barging Sergeant
abilities=haste
auto=@combat(attacking) source(this):this(power=0) counter(1/1,1) target(other creature[attacking;power<0]|myBattlefield)
auto=@combat(attacking) source(this):this(power=1) counter(1/1,1) target(other creature[attacking;power<=0]|myBattlefield)
auto=@combat(attacking) source(this):this(power=2) counter(1/1,1) target(other creature[attacking;power<=1]|myBattlefield)
auto=@combat(attacking) source(this):this(power=3) counter(1/1,1) target(other creature[attacking;power<=2]|myBattlefield)
auto=@combat(attacking) source(this):this(power=4) counter(1/1,1) target(other creature[attacking;power<=3]|myBattlefield)
auto=@combat(attacking) source(this):this(power=5) counter(1/1,1) target(other creature[attacking;power<=4]|myBattlefield)
auto=@combat(attacking) source(this):this(power=6) counter(1/1,1) target(other creature[attacking;power<=5]|myBattlefield)
auto=@combat(attacking) source(this):this(power=7) counter(1/1,1) target(other creature[attacking;power<=6]|myBattlefield)
auto=@combat(attacking) source(this):this(power=8) counter(1/1,1) target(other creature[attacking;power<=7]|myBattlefield)
auto=@combat(attacking) source(this):this(power=9) counter(1/1,1) target(other creature[attacking;power<=8]|myBattlefield)
auto=@combat(attacking) source(this):this(power=10) counter(1/1,1) target(other creature[attacking;power<=9]|myBattlefield)
auto=@combat(attacking) source(this):this(power=11) counter(1/1,1) target(other creature[attacking;power<=10]|myBattlefield)
auto=@combat(attacking) source(this):this(power=12) counter(1/1,1) target(other creature[attacking;power<=11]|myBattlefield)
auto=@combat(attacking) source(this):this(power=13) counter(1/1,1) target(other creature[attacking;power<=12]|myBattlefield)
auto=@combat(attacking) source(this):this(power=14) counter(1/1,1) target(other creature[attacking;power<=13]|myBattlefield)
auto=@combat(attacking) source(this):this(power=15) counter(1/1,1) target(other creature[attacking;power<=14]|myBattlefield)
auto=@combat(attacking) source(this):this(power=16) counter(1/1,1) target(other creature[attacking;power<=15]|myBattlefield)
auto=@combat(attacking) source(this):this(power=17) counter(1/1,1) target(other creature[attacking;power<=16]|myBattlefield)
auto=@combat(attacking) source(this):this(power=18) counter(1/1,1) target(other creature[attacking;power<=17]|myBattlefield)
auto=@combat(attacking) source(this):this(power=19) counter(1/1,1) target(other creature[attacking;power<=18]|myBattlefield)
auto=@combat(attacking) source(this):this(power=20) counter(1/1,1) target(other creature[attacking;power<=19]|myBattlefield)
auto=@combat(attacking) source(this):this(power>=21) counter(1/1,1) target(other creature[attacking;power<=20]|myBattlefield)
text=Haste -- Mentor (Whenever this creature attacks, put a +1/+1 counter on target attacking creature with lesser power.)
mana={4}{R}
type=Creature
subtype=Minotaur Soldier
power=4
toughness=2
[/card]

Rebound:
[card]
name=Virulent Swipe
target=creature
auto=2/0 ueot
auto=deachtouch ueot
auto=if rebound then ability$!moveto(exile) all(Virulent Swipe|mystack)!$ controller
autoexile=@rebounded:may activate castcard(normal)
text=Target creature gets +2/+0 and gains deathtouch until end of turn. -- Rebound (If you cast this spell from your hand, exile it as it resolves. At the beginning of your next upkeep, you may cast this card from exile without paying its mana cost.)
mana={B}
type=Instant
[/card]

About Containment Membrane just try this:
[card]
name=Containment Membrane
target=creature
auto=doesnotuntap
text=Surge {U} (You may cast this spell for its surge cost if you or a teammate has cast another spell this turn.) -- Enchant creature -- Enchanted creature doesn't untap during its controller's untap step.
mana={2}{U}
other={U} name(surge)
otherrestriction=thisturn(*|mystack)~morethan~0
type=Enchantment
subtype=Aura
[/card]

Let me know if they work so i can update all the similar cards for next release (i guess in August).

**Comment by luisguerin** [comment]
OK, thanks for this.
But i dont know how to use this to test

Em dom, 26 de jul de 2020 13:17, Vittorio Alfieri <notifications@github.com>
escreveu:

**Comment by Vitty85** [comment]
You have just to replace those cards in mtg.txt and borderline.txt. those files are in Res/sets/primitives folder.

Let me know if you can do it.

**Comment by Vitty85** [comment]
Or just use those files.

[borderline.txt](https://github.com/WagicProject/wagic/files/4977936/borderline.txt)
[mtg.txt](https://github.com/WagicProject/wagic/files/4977937/mtg.txt)
[unsupported.txt](https://github.com/WagicProject/wagic/files/4977938/unsupported.txt)

**Comment by luisguerin** [comment]
Thanks i will try this

Em dom, 26 de jul de 2020 13:36, Vittorio Alfieri <notifications@github.com>
escreveu:

**Comment by luisguerin** [comment]
OK i tested,
Rebound is working! Pretty good! It even ask in my unkeep to activate or
not the spell again, no problems.
Mentor seems to be working, but it is checking all the possibilities so it
is like activating a loooot of abilities at same time, making really boring
to skip all of them, specially when there is more than one mentor, in this
case, seems that the same mentor could put more than one counter if i
increase its power in the process, (if another mentor put a counter in it,
it put two counters in other creatures, one for its power before receive a
counter and another after receive a counter) . maybe is there another way
for this...
Containment menbrane is working now.
Thanks


Em dom, 26 de jul de 2020 13:43, Luis Guerin <luiscguerin@gmail.com>
escreveu:

**Comment by Vitty85** [comment]
Ok,

Maybe i solved Mentor too, can you test again this?

[card]
name=Barging Sergeant
abilities=haste
auto=@combat(attacking) source(this) restriction{compare(p)~lessthan~1}:counter(1/1,1) target(other creature[attacking;power<=-1]|myBattlefield)
auto=@combat(attacking) source(this) restriction{compare(p)~equalto~1}:counter(1/1,1) target(other creature[attacking;power<=0]|myBattlefield)
auto=@combat(attacking) source(this) restriction{compare(p)~equalto~2}:counter(1/1,1) target(other creature[attacking;power<=1]|myBattlefield)
auto=@combat(attacking) source(this) restriction{compare(p)~equalto~3}:counter(1/1,1) target(other creature[attacking;power<=2]|myBattlefield)
auto=@combat(attacking) source(this) restriction{compare(p)~equalto~4}:counter(1/1,1) target(other creature[attacking;power<=3]|myBattlefield)
auto=@combat(attacking) source(this) restriction{compare(p)~equalto~5}:counter(1/1,1) target(other creature[attacking;power<=4]|myBattlefield)
auto=@combat(attacking) source(this) restriction{compare(p)~equalto~6}:counter(1/1,1) target(other creature[attacking;power<=5]|myBattlefield)
auto=@combat(attacking) source(this) restriction{compare(p)~equalto~7}:counter(1/1,1) target(other creature[attacking;power<=6]|myBattlefield)
auto=@combat(attacking) source(this) restriction{compare(p)~equalto~8}:counter(1/1,1) target(other creature[attacking;power<=7]|myBattlefield)
auto=@combat(attacking) source(this) restriction{compare(p)~equalto~9}:counter(1/1,1) target(other creature[attacking;power<=8]|myBattlefield)
auto=@combat(attacking) source(this) restriction{compare(p)~equalto~10}:counter(1/1,1) target(other creature[attacking;power<=9]|myBattlefield)
auto=@combat(attacking) source(this) restriction{compare(p)~equalto~11}:counter(1/1,1) target(other creature[attacking;power<=10]|myBattlefield)
auto=@combat(attacking) source(this) restriction{compare(p)~equalto~12}:counter(1/1,1) target(other creature[attacking;power<=11]|myBattlefield)
auto=@combat(attacking) source(this) restriction{compare(p)~equalto~13}:counter(1/1,1) target(other creature[attacking;power<=12]|myBattlefield)
auto=@combat(attacking) source(this) restriction{compare(p)~equalto~14}:counter(1/1,1) target(other creature[attacking;power<=13]|myBattlefield)
auto=@combat(attacking) source(this) restriction{compare(p)~equalto~15}:counter(1/1,1) target(other creature[attacking;power<=14]|myBattlefield)
auto=@combat(attacking) source(this) restriction{compare(p)~equalto~16}:counter(1/1,1) target(other creature[attacking;power<=15]|myBattlefield)
auto=@combat(attacking) source(this) restriction{compare(p)~equalto~17}:counter(1/1,1) target(other creature[attacking;power<=16]|myBattlefield)
auto=@combat(attacking) source(this) restriction{compare(p)~equalto~18}:counter(1/1,1) target(other creature[attacking;power<=17]|myBattlefield)
auto=@combat(attacking) source(this) restriction{compare(p)~equalto~19}:counter(1/1,1) target(other creature[attacking;power<=18]|myBattlefield)
auto=@combat(attacking) source(this) restriction{compare(p)~equalto~20}:counter(1/1,1) target(other creature[attacking;power<=19]|myBattlefield)
auto=@combat(attacking) source(this) restriction{compare(p)~morethan~20}:counter(1/1,1) target(other creature[attacking;power<=20]|myBattlefield)
text=Haste -- Mentor (Whenever this creature attacks, put a +1/+1 counter on target attacking creature with lesser power.)
mana={4}{R}
type=Creature
subtype=Minotaur Soldier
power=4
toughness=2
[/card]

or just replace this file:
[borderline.txt](https://github.com/WagicProject/wagic/files/4978247/borderline.txt)

Let me know.

**Comment by luisguerin** [comment]
i will test right now,
i thought you have corrected just one card but actually all cards with
rebound are now working.
thanks a lot for this!

Em dom., 26 de jul. de 2020 às 16:22, Vittorio Alfieri <
notifications@github.com> escreveu:

**Comment by Vitty85** [comment]
Actually in this new file i corrected also all mentor cards:
[borderline.txt](https://github.com/WagicProject/wagic/files/4978292/borderline.txt)

Probably in next release i will add even the filter option ;)

**Comment by luisguerin** [comment]
i have tested , this time worked very well.
Thanks a lot!

Em dom., 26 de jul. de 2020 às 16:55, Vittorio Alfieri <
notifications@github.com> escreveu:

**Comment by Vitty85** [comment]
Nice to hear that! 

So, in next August release you will find the filter option too.

I will not change the version number but i will just update the current release to Double Masters set.

Stay tuned and see you soon.
