### ISSUE TITLE
Crash on psp

### ISSUE THREAD

**Issue by ALittlePatate** [WagicProject/wagic#1036]
Wagic v0.22.3 for psp is crashing (and turning of my psp) on a PSP Street during the loading

**Comment by Vitty85** [comment]
I'm afraid that nowadays the last PSP version can run just on PSVita with Adrenaline due to the High memory profile (64Mb) and CPU performance (333Mhz) requested.

Maybe it could work on a PSP-3000 but i'm not 100% sure of this since i cannot test on that device.

**Comment by ALittlePatate** [comment]
> I'm afraid that nowadays the last PSP version can run just on PSVita with Adrenaline due to the High memory profile (64Mb) and CPU performance (333Mhz) requested.
> 
> Maybe it could work on a PSP-3000 but i'm not 100% sure of this since i cannot test on that device.

Oh okay, so that's normal then. What version should i use ?

**Comment by Vitty85** [comment]
I’m not sure 100% but I guess the last working on old PSP is v0.19.2 (you can find it in release page), but I couldn’t try it since I don’t have a PSP.

See you.

--
Inviato da iPhone

**Comment by ALittlePatate** [comment]
i cant' find any download link for the psp on the v0.19.2 release

**Comment by Vitty85** [comment]
Try with those links:

Eboot
http://cdn-0.wololo.net/files/wagic/WTH_0190_r4789.zip

Core 
https://github.com/WagicProject/wagic/releases/download/wagic-v0.19.2/core_0192.zip

Btw you can even follow the wagic forum:
http://wololo.net/forum/index.php

See you.

--
Inviato da iPhone

**Comment by ALittlePatate** [comment]
okay, i have another problem, the game crashed and gave me that :

Exception details:

Exception - Bus error (data)
EPC       - 08AA59B0 / JGEApp_Title.text + 002A19B0
Cause     - 1000001C
Status    - 20008613
BadVAddr  - FDC57E04
zr:00000000 at:DEADBEEF v0:00000001 v1:08C8A8DC
a0:08C8A820 a1:00000000 a2:08C8A820 a3:08C8A820
t0:00000000 t1:00000080 t2:08B6098C t3:08C8A80C
t4:00000000 t5:DEADBEEF t6:DEADBEEF t7:DEADBEEF
s0:00000000 s1:08C8A820 s2:08C84D70 s3:08A67FF8
s4:08C8A580 s5:09FBF99C s6:09FBF998 s7:09FBF9B8
t8:DEADBEEF t9:DEADBEEF k0:09FBFF00 k1:00000000
gp:08B69050 sp:09FBF910 fp:08C72060 ra:08A3BF68

**Comment by Vitty85** [comment]
So I’m afraid you have to go back to 0.18.6 version...

https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/wagic/WTH_0186_PSP_Unsigned.zip

If I will find another version I will send you link.

See you.

--
Inviato da iPhone

**Comment by ALittlePatate** [comment]
It's working, thank you !
