### ISSUE TITLE
Cards that dont work

### ISSUE THREAD

**Issue by luisguerin** [WagicProject/wagic#1037]
I made a little list of cards that i've tried to use  this month and they didnt worked properly.
. supernatural stamina - creature doesnt return to Field
. dread wanderer -   cant cast from grave
. time to reflect - can't activate
. temmet, vizier of naktamun - ability wich gives +1/+1 and unblockable doesn't activate
. expose evil - is putting 2 clues instead of 1
. virulent swipe - creature is not gaining death touch
. rosethorn halberd - the game just crashes after I chose target to equip after cast it
. shining armor - game crash, just like rosethorn halberd
. thornbite staff - the ability to deal 1 damage to target creature or player is dealing damage to the equipped creature instead
. merfolk trickster - it's not activating the effect wich tap an opponent creature
. naban, Dean of iteration - does nothing
. academy journeymage - can't cast it for 1 mana less
. fireblade artist - his effect is sacrificing a creature but it's not doing damage to the opponent
. rakdos firewheeler - it's asking if I want to deal 2 damage to opponent OR to a creature, instead of doing the two things one after another
.moment of triumph - can't cast at all
. neheb, the worthy - his effect of giving +2/+0 to other Minotaurs in player control does not work, the other effects are OK
. Heart-piercer manticore - after it enters in field and I choose a creature to sacrifice I can't choose a target for damage, the sacrificed creature is  going to the grave with the damage in it
. hazoret's favor - it is just staying in field without doing nothing, can't activate the effect
. fireball - it's not working
. warfire javelineer - it is doing just 1 point of damage upon entering the field instead of x = number of instants and sorceries in grave, and after that, for some reason it's doing 1 damage each time I activate a instant or sorcery while it's in the field
. soul-scar mage - it does nothing
. insult - effect of doble damage doesn't work

This is it for now :)
By the way, I know there are more cards that don't work the way they're supposed to do, it's okay if I bring other list(s) like this?
Another question, some cards aren't in the game because their effects aren't supported(I imagine),
But sometimes there are cards that seams plausible to work, what comes to my mind at the moment are the dimir cards from guilds of ravnica pack , the cards that surveil are there, but the cards that combo with surveil activating another effect each time you surveil aren't there. it's possible to add this cards?
And just one more thing, I don't know if it already exists in the game but it's possible to make a game mode for commander format?
Thanks

**Comment by Vitty85** [comment]
Leave the card list also here, http://wololo.net/forum/viewtopic.php?f=4&p=99951&sid=25ef81dd5bf7f03ba96f857c76cb2755#p99951

i can take a look when it's possible and try to add them in next releases.

For Commander mode i cannot give any update right now.

See you.

**Comment by Vitty85** [comment]
> dimir



> I made a little list of cards that i've tried to use this month and they didnt worked properly.
> . supernatural stamina - creature doesnt return to Field
> . dread wanderer - cant cast from grave
> . time to reflect - can't activate
> . temmet, vizier of naktamun - ability wich gives +1/+1 and unblockable doesn't activate
> . expose evil - is putting 2 clues instead of 1
> . virulent swipe - creature is not gaining death touch
> . rosethorn halberd - the game just crashes after I chose target to equip after cast it
> . shining armor - game crash, just like rosethorn halberd
> . thornbite staff - the ability to deal 1 damage to target creature or player is dealing damage to the equipped creature instead
> . merfolk trickster - it's not activating the effect wich tap an opponent creature
> . naban, Dean of iteration - does nothing
> . academy journeymage - can't cast it for 1 mana less
> . fireblade artist - his effect is sacrificing a creature but it's not doing damage to the opponent
> . rakdos firewheeler - it's asking if I want to deal 2 damage to opponent OR to a creature, instead of doing the two things one after another
> .moment of triumph - can't cast at all
> . neheb, the worthy - his effect of giving +2/+0 to other Minotaurs in player control does not work, the other effects are OK
> . Heart-piercer manticore - after it enters in field and I choose a creature to sacrifice I can't choose a target for damage, the sacrificed creature is going to the grave with the damage in it
> . hazoret's favor - it is just staying in field without doing nothing, can't activate the effect
> . fireball - it's not working
> . warfire javelineer - it is doing just 1 point of damage upon entering the field instead of x = number of instants and sorceries in grave, and after that, for some reason it's doing 1 damage each time I activate a instant or sorcery while it's in the field
> . soul-scar mage - it does nothing
> . insult - effect of doble damage doesn't work
> 
> This is it for now :)
> By the way, I know there are more cards that don't work the way they're supposed to do, it's okay if I bring other list(s) like this?
> Another question, some cards aren't in the game because their effects aren't supported(I imagine),
> But sometimes there are cards that seams plausible to work, what comes to my mind at the moment are the dimir cards from guilds of ravnica pack , the cards that surveil are there, but the cards that combo with surveil activating another effect each time you surveil aren't there. it's possible to add this cards?
> And just one more thing, I don't know if it already exists in the game but it's possible to make a game mode for commander format?
> Thanks

Hi,

I fixed all the cards in your list except Naban, Dean of Iteration because there is no way to double trigger the activated abilities at the moment.

I just updated the 0.22.3 Wagic Release so you can download it again and test so see if it's all ok: 
https://github.com/WagicProject/wagic/releases/tag/wagic-v0.22.3

I took a look as Surveil trigger, i'm sorry but actually there is no way to set a listener for that event since there is no a specific surveil ability, the game uses a Reveal keyword with some tricks, so it should require enough work to create something like you ask and for the moment it not possible.

Let me know if the card i corrected are working for you too and let me know if there are other cards to fix, see you soon.

**Comment by Vitty85** [comment]
Hi,

I just released the 0.23.1 Wagic Release and I implemented the Commander Format and a lot of other features too, If you want you can download it  from the official link:
https://github.com/WagicProject/wagic/releases/tag/wagic-v0.23.1

See you soon.

**Comment by luisguerin** [comment]
Hey,
Thanks for remember me...
And sorry for beeing this late :)
I was very occupied with my university
I will install this new version, if anything comes up I will make you know
Thank you!

PS. This has nothing to do with wagic, I made a Christmas video with my
music group (classical music, I play violin ), it's in Portuguese but the
music speaks for itself, you don't have to,  but if you in that mood, it's
less than 20min...
https://youtu.be/FZF8s20vJgM

Em qui, 10 de dez de 2020 07:03, Vittorio Alfieri <notifications@github.com>
escreveu:

**Comment by Darthagnon** [comment]
@luisguerin que musica mais bonita! Um feliz natal para vôçes!

**Comment by luisguerin** [comment]
Muito Agradecido
É apenas um singelo gesto de carinho.
Boas festas!

Em seg, 21 de dez de 2020 22:03, Darren John de Lima <
notifications@github.com> escreveu:
