### ISSUE TITLE
PSP ver 0.223 won't run

### ISSUE THREAD

**Issue by WaffleSyrup** [WagicProject/wagic#1038]
I recently installed CFW 6.61 on my PSP 3000 and I'm trying to install the newest version of Wagic but after I select a language my PSP shuts itself off while on "Loading Primitives". I've looked everywhere for a fix but nothing seems to work. I've added no images or mods, only the base game. How can I get the game to actually run?

**Comment by Vitty85** [comment]
Hi,

I guess the actual huge number of primitives and sets is really hard for PSP to be supported. I tested the game on PSVita with Adrenaline emulator (High memory profile enabled and CPU set to 333Mhz) and it's working quite fine.

I'm afraid it cannot load properly on your PSP, you can maybe try to remove some sets and some primitives from the Res folder, it can be one hope to make the game running on that device. Also try to reduce the size of your collection.dat file in the User folder.

Hope it can be helpful, see you.
