### ISSUE TITLE
Doubling Season card cause's the game crash

### ISSUE THREAD

**Issue by DoidArthas** [WagicProject/wagic#1040]
When the card effect activate, the game crash

**Comment by Vitty85** [comment]
Hi,

I tested on last version and it does not crash to me...

If you give me other details i can take another look:

Can you say when you download last exe from GITHUB? 
Can you say which platform are you using to play: Win?, Linux?, Android? PSVita?
Can you say which combo creates you problem? Doubling Season + which other card? 

Let me know, see you.

**Comment by DoidArthas** [comment]
Ok I Will download. You asked for more information.
I am using windows, building a Green elven deck. When the token creation begins, It crashes. And the card "Rhys The redeemed" second effect cause's crash too, its token creation again

**Comment by Vitty85** [comment]
Yes I asked but then I found the bug even with my tests, now It should be ok.

Let me know.

--
Inviato da iPhone
