### ISSUE TITLE
How to run in Ubuntu?

### ISSUE THREAD

**Issue by DoidArthas** [WagicProject/wagic#1041]
I've downloaded the game in the main page for linux. So, how do I run the game?

**Comment by Vitty85** [comment]
Hi,

You have 2 options, use the X11 version or QT version.

It's enough to unpack the zip file in a Linux Machine and run ./Wagic or ./Wagic_X11 executable in the same folder you unpacked, it should be very easy and i generally test game in Ubuntu after compiling it.

Let me know, see you.

**Comment by DoidArthas** [comment]
I tried running with the software manager and nothing happened. I will try that. You know how can I make a shortcut for It?

**Comment by DoidArthas** [comment]
So, the game Works fine. Bot the shortcuts are others than windows, and the mouse does not work

**Comment by Vitty85** [comment]
Wait a minute...

With the Wagic_X11 of course no Sound and no Mouse working, that's normal.

With the QT version (just Wagic file) the sound and the mouse are working properly.

You just have to open a shell, enter the folder you extracted the files and run ./Wagic that's all.

See you.

**Comment by Vitty85** [comment]
Of course be sure you have installed the QT libraries dependencies with apt-get or package manager first.
