### ISSUE TITLE
Can't start windows version, and PSP version gets stuck at "loading primitives" infinitely

### ISSUE THREAD

**Issue by Saftur** [WagicProject/wagic#1042]
I'm using Windows 10. I've tried installing visual studio redistributables, and I've tried running in compatibility mode, but it just does nothing every time I try to start it. I get a loading cursor for a few seconds, but it soon goes away, and nothing else happens, not even an error window.

As for the PSP version; I'm not using CFW. I've tried using both the normal & unsigned EBOOT files. It gets stuck on "loading primitives" with both. Also, I would think if there's one called "UNSIGNED", then the other one is signed and I can run it directly from the PSP menu, but it says it's corrupted, and I have to launch it through HBL.

**Comment by Vitty85** [comment]
Hi,

About the PSP i'm afraid the CPU and the RAM of your model are not enough to run the last version of game, i tried the PSP version just on PSVita with Adrenaline Emulator. You can try to manually remove some sets and cards from Res/sets folder, it could be helpful maybe.

About Win 10 i don't know, it's working fine on both my laptop with that OS, without any other detail i don't have idea how to be helpful, i'm sorry.

See you.

**Comment by Saftur** [comment]
Ah, sorry about my lack of details, I'm not used to reporting issues like this.

Here are my redistributables right now:
![image](https://user-images.githubusercontent.com/9270842/100133623-dcf62880-2e3b-11eb-82d7-2fa8e7261afc.png)

Here are some details, I'm not sure what else I should give:
Processor: Intel I7
RAM: 16 GB
System type: 64 bit OS & processor
Windows version: Windows 10 Home; Version 2004
GPU: NVIDIA GeForce GTX 1060 3GB

**Comment by Saftur** [comment]
Also, how come the regular EBOOT doesn't work without HBL? I've used an older version of wagic, and it worked without HBL.

**Comment by Saftur** [comment]
I tried removing a bunch of sets on the PSP version. Now it doesn't even get to the "loading primitives" screen.

**Comment by Vitty85** [comment]
About HBL, try to use the unsigned eboot.

About removing sets you have to remove even primitives, and also I cannot promise it will ever work on PSP, the RAM is really less on that device and now the number of cards and sets is really increased comparing to older versions.

About win 10 I still don’t know what’s wrong with your pc, I tried on 3 different pc and I have no issue, the exe is starting without any difficulties... can you start the exe in command shell to see if there is a trace of the error? Just open cmd.exe, go to Wagic folder and run Wagic.exe to see what it will show on command line.

See you.

**Comment by Saftur** [comment]
I'll just give up on the PSP version then. As for the windows version, it doesn't say anything when I run it in cmd.

**Comment by Vitty85** [comment]
Just to try, select all the dlls in the folder of game and drag them over the exe file, it should force it to reload them, I really have no idea what’s wrong actually...

**Comment by Saftur** [comment]
That didn't work either.

I might try to compile the source myself later, might be able to figure something out that way.

**Comment by Vitty85** [comment]
Sure you can compile with VS10.

Just to be sure you download the 0.22.3 release from this link? https://github.com/WagicProject/wagic/releases/download/wagic-v0.22.3/WagicWindows-0223.zip

I just download it and extract again and it worked, so strange...

**Comment by Saftur** [comment]
Yeah, that's the link I used.

**Comment by Saftur** [comment]
I tried redownloading it just now, and it seems like when I run it for the first time, I get a Windows Smartscreen popup, but it still does nothing after that.

**Comment by Vitty85** [comment]
Can you screenshot that ?

**Comment by Saftur** [comment]
![image](https://user-images.githubusercontent.com/9270842/100154506-8b10cb00-2e5a-11eb-9287-34fd84bf1002.png)

**Comment by Vitty85** [comment]
Can you try to disable windows defender before to launch exe?

**Comment by Saftur** [comment]
I disabled SmartScreen, and now it says this:
![100155826-c6ac9480-2e5c-11eb-9452-4046c3370902](https://user-images.githubusercontent.com/9270842/100156200-5ce0ba80-2e5d-11eb-974c-0e4d2df0a857.png)
This is the thing I disabled:
![image](https://user-images.githubusercontent.com/9270842/100155957-fd82aa80-2e5c-11eb-8a39-3c2fccf3af1e.png)
I don't really see any option to disable Defender in its entirety.

**Comment by Vitty85** [comment]
You extract the zip right? Can you screenshot the folder of exe?

**Comment by Saftur** [comment]
![image](https://user-images.githubusercontent.com/9270842/100156599-0aec6480-2e5e-11eb-9fc3-c85b30076f3c.png)

**Comment by Vitty85** [comment]
Seems correct... can you try to run with admin privileges? Also to close defender it’s enough to kill process with task manager.

**Comment by Saftur** [comment]
Admin privileges didn't work. And to be honest, I'm a little reluctant to kill the defender process. I'd rather just try building it myself later.

**Comment by Vitty85** [comment]
I got it, let me know if it works, I can also try to build files in debug mode and send you new exe and dlls.

See you.

**Comment by blaise-rascal** [comment]
Just want to chime in and say that I used to also have the issue where the game would not start on Windows 10, and there was no indication as to why. But running it as administrator fixed the issue.

**Comment by Vitty85** [comment]
Ok,

I’m my pc I don’t have to use admin privileges…

By the way I guess I fixed also the psp version problem, you should follow these steps:

Download the latest version of Wagic for PSP from official link.
Delete (or reduce a lot) the file "collection.dat" from your "User/player" folder.
Download the file "LimitedCardList.txt" (https://github.com/WagicProject/wagic/releases/latest/download/LimitedCardList.txt) and copy it into your "User" folder.
Rename or remove the "graphics" sub-folder in your Res folder (of course you should firstly unzip the core file).
Download the file "graphicsPSP.zip" (https://mega.nz/file/6DYmTZ7Z#UiFcMs4rm3PM4OH3w1cjQmS8-P7XGJ8EUrg0Ta9A4OY) and extract it into your "Res" folder.
Use the default theme with no audio.
Start the game.
See you.

--
Inviato da iPhone

**Comment by blaise-rascal** [comment]
Perhaps I spoke too soon - oddly enough, it appears to no longer work, even with admin privileges. Maybe the real reason it worked once, is that I opened it soon after startup, before some Windows process was loaded to shut it down? Oh well.

**Comment by Vitty85** [comment]
Can be, maybe it's your defender or something like that...

Il Ven 3 Set 2021, 20:28 blaise-rascal ***@***.***> ha
scritto:

**Comment by blaise-rascal** [comment]
Well, disabling defender didn't help, but setting compatibility to windows 7 seemed to fix the issue consistently for current and past versions of wagic. NICE!

**Comment by Vitty85** [comment]
Nice, I’m happy you found a solution!

--
Inviato da iPhone
