### ISSUE TITLE
Jace, Vrin's Prodigy does not work

### ISSUE THREAD

**Issue by DoidArthas** [WagicProject/wagic#1044]
Even whit the conditions solved, Jace is not exiled and the effect does not proceed

**Comment by Vitty85** [comment]
You are right,

Both side of that card had some issues...

By the wayi fixed tham and so these are the corrected primitives for both sides:

[card]
name=Jace, Vryn's Prodigy
auto={T}:draw:1 controller && ability$!name(Discard a card) reject notatarget(*|myhand)!$ controller restriction{type(*|mygraveyard)~lessthan~4}
auto={T}:draw:1 controller && ability$!name(Discard a card) reject notatarget(*|myhand)!$ controller && moveto(exile) and!( moveto(mybattlefield) and!( haste && counter(0/0,5,Loyalty) && flip(Jace, Telepath Unbound) )! )! restriction{type(*|mygraveyard)~morethan~3}
text={T}: Draw a card, then discard a card. If there are five or more cards in your graveyard, exile Jace, Vryn's Prodigy, then return him to the battlefield transformed under his owner's control.
mana={1}{U}
type=Legendary Creature
subtype=Human Wizard
power=0
toughness=2
[/card]

[card]
name=Jace, Telepath Unbound
auto=counter(0/0,5,loyalty)
auto={C(0/0,1,Loyalty)}:name(+1: don't target any creature) donothing
auto={C(0/0,1,Loyalty)}:name(+1: target creature gets -2/0) may target(creature) -2/0 uynt
auto={C(0/0,-3,Loyalty)}:name(-3: choose an instant or sorcery you may from graveyard) target(*[instant;sorcery]|mygraveyard) transforms((,newability[canplayfromgraveyard],newability[gainedexiledeath])) ueot
auto={C(0/0,-9,Loyalty)}:name(-9: emblem mills opponent cards) emblem transforms((,newability[@movedTo(*|mystack):deplete:5 opponent])) forever dontremove
text=+1: Up to one target creature gets -2/-0 until your next turn. -- -3: You may cast target instant or sorcery card from your graveyard this turn. If that card would be put into your graveyard this turn, exile it instead. -- -9: You get an emblem with "Whenever you cast a spell, target opponent puts the top five cards of his or her library into his or her graveyard."
type=Legendary Planeswalker
subtype=Jace
color=blue
[/card]

If you want to test you can manually replace the old versions with these in borderline.txt and planeswalkers.txt files, I will update them in next release, see you soon.

**Comment by Vitty85** [comment]
Closed in the current release, you can download the last release on official link.
