### ISSUE TITLE
Scion of ur dragon

### ISSUE THREAD

**Issue by ranger7271** [WagicProject/wagic#1045]
Copies another dragon but does not end at the end of the turn.

**Comment by ranger7271** [comment]
Cavern of skulls

Seems to create any Mana no matter what you cast.

**Comment by Vitty85** [comment]
Scion of dragon will be fixed with next release, but Cavern of skulls cannot be fixed, there is no way to add mana just for specific cast, sorry.

**Comment by Vitty85** [comment]
Closed in latest version available from the official release link.

**Comment by ranger7271** [comment]
I figured the cavern was too weird to fix

The player can just use it on the honor system

**Comment by Vitty85** [comment]
But at least now it's not adding mana if you don't have a creature of that
time in your hand or commandzone. I guess it's close enough.

See you.

Il Mer 23 Dic 2020, 13:29 ranger7271 <notifications@github.com> ha scritto:
