### ISSUE TITLE
Story Mode broken Android 0.23

### ISSUE THREAD

**Issue by 3xpFlameS** [WagicProject/wagic#1046]
Hi,
Just installed the latest update. 
Unfortunately the story mode only shows the first episode. No second chapter appears. Playing on Huawei P30 Pro

**Comment by 3xpFlameS** [comment]
I replayed now. After the first match it says I need to hit the "action button" to go back to main menu. I can only choose two options: "back to main" or "cancel"
No matter which I choose I end up in main menu. However going back to story mode I only have episode 1.
How do I get to episode 2?

**Comment by Vitty85** [comment]
Hi,

There is no chapter 2... the first one is just one sample.

Long time no one create new stories i'm sorry...

I added a story in my User folder named borther war, you can download it from here and unzip in your User/campaign folder:

https://mega.nz/file/rCpRGS6R#s1rlpI97xsaUTk7HHJju26diA8oGltMNf3uR_VFFP2c

See you.
