### ISSUE TITLE
Edgar Marvov

### ISSUE THREAD

**Issue by ranger7271** [WagicProject/wagic#1047]
Does not create vampires when he's in the command zone or battlefield

**Comment by Vitty85** [comment]
I guess i understood the error, you can try with this code:

`[card]`
`name=Edgar Markov`
`abilities=first strike,haste`
`auto=@movedTo(other creature[vampire]|mystack):token(Vampire,Creature Vampire,1/1,black)`
`autocommandzone=@movedTo(other creature[vampire]|mystack):token(Vampire,Creature Vampire,1/1,black)`
`auto=@combat(attacking) source(this):counter(1/1) all(vampire|myBattlefield)`
`text=Eminence — Whenever you cast another Vampire spell, if Edgar Markov is in the command zone or on the battlefield, create a 1/1 black Vampire creature token. -- First strike, haste -- Whenever Edgar Markov attacks, put a +1/+1 counter on each Vampire you control.`
`mana={3}{R}{W}{B}`
`type=Legendary Creature`
`subtype=Vampire Knight`
`power=4`
`toughness=4`
`[/card]`

Let me know if it works so i can update the game., see you.

**Comment by Vitty85** [comment]
Closed with last update available on official release page.
