### ISSUE TITLE
Game Crashes Constantly on Huawei (Android) 

### ISSUE THREAD

**Issue by 3xpFlameS** [WagicProject/wagic#1048]
Hi team,
My version 0.23 constantly crashes. 
Most often this happens during classic mode against any opponent. But it also happens in shop and Co at some times.
Playing on Huawei P30 Pro with Android 10

On first start I got the message: "this app has been developed for an older built, it might not function properly."

Do you know a fix for the crashing?

**Comment by Vitty85** [comment]
Hi,

I'm currently playing on Samsung A8 running Android 9 without any problem, i have no idea what's wrong with Android 10 since i don't have a device with that firmware at the moment.

Actually I'm not sure i can recompile the APK with a newer SDK without loosing retro-compatibility... I will take a look but since i cannot make any test on my own i cannot promise anything, i'm sorry.

See you.

**Comment by Vitty85** [comment]
> Hi team,
> My version 0.23 constantly crashes.
> Most often this happens during classic mode against any opponent. But it also happens in shop and Co at some times.
> Playing on Huawei P30 Pro with Android 10
> 
> On first start I got the message: "this app has been developed for an older built, it might not function properly."
> 
> Do you know a fix for the crashing?

Hi,

I need some other infos if it's possibile:

1) Are you using a custom theme with custom audio files?
2) Are you using some specific decks or cards or it's crashing independently?

Thanks, see you.

**Comment by Vitty85** [comment]
Try to mute sound both for music and effect, i'm guessing it can depends on that, maybe a memory failure on some samples.

**Comment by Vitty85** [comment]
I recompiled the APK with latest SDK and NDK and i tested with a Samsung S10 with Android 10. I could be able to play for more than 1 hour without crashes, i'm not sure it solved 100% but at least it's not crashing in short time.

I played with sound too, but i guess without sounds the game can continue longer, probably there is some issue on memory allocation of SDL in Android 10, i don't know exactly.

You can download the new APK from same link in GitHub release, let me know if it's working better on your phone too.

See you soon.

**Comment by 3xpFlameS** [comment]
Alright thank you I will test it.
Fi, I played with different cards but music wasn't muted. So I will do now and let you know

**Comment by 3xpFlameS** [comment]
OK now I cannot start the game anymore. It gives the attached error msg.
It did not ask for any permissions when starting the app. 
![Screenshot_20201227_084653_net wagic app](https://user-images.githubusercontent.com/9251947/103166244-712f2300-4820-11eb-9704-3fb402c7b450.jpg)

**Comment by 3xpFlameS** [comment]
OK that one I solved. I needed to click on the storage location in the first screen (SD card) even though it was marked

**Comment by 3xpFlameS** [comment]
New issue... I don't have any cards to play. I tried with standard deck and with a newly created one. They do not show
![Screenshot_20201227_092755_net wagic app](https://user-images.githubusercontent.com/9251947/103166859-87d87880-4826-11eb-8a8f-eb3884d35ab9.jpg)
![Uploading Screenshot_20201227_093215_net.wagic.app.jpg…]()

**Comment by Vitty85** [comment]
I guess your collection is empty... or you are using a deck containing cards you don’t own.

Can you take a look to your collection.dat file?

Also, 

Can you download the full user folder from here and try again?

https://mega.nz/file/XPpmGCbY#4uLyzJy_-PRsrnCEdRkYtpjaCBaNauSOt-8SDj3uEus

Generally you can follow the evolution of games in the forum:

https://wololo.net/forum/viewtopic.php?f=17&t=66595&start=20#p99279

Hope it can work, let me know.


--
Inviato da iPhone

**Comment by 3xpFlameS** [comment]
That worked perfectly thanks!

**Comment by Vitty85** [comment]
Nice, so I close the issue now, see you soon.

**Comment by 3xpFlameS** [comment]
So I now tested it a few days. Unfortunately it still crashes in classic mode very frequently. Other than the first match I could not battle any other rivals as at one point in the game it always crashes...

**Comment by Vitty85** [comment]
Since i did not have any crashes i need your deck, maybe there is a problem
with it, on samsung note 10 and samsung S10 no crashe occurres.

See you.

Il Mer 30 Dic 2020, 11:10 3xpFlameS <notifications@github.com> ha scritto:

**Comment by 3xpFlameS** [comment]
![Uploading Screenshot_20210102_210433_net.wagic.app.jpg…]()
![Screenshot_20210102_210417_net wagic app](https://user-images.githubusercontent.com/9251947/103465647-30626d00-4d3e-11eb-9ba2-299462a3fedd.jpg)
![Screenshot_20210102_210422_net wagic app](https://user-images.githubusercontent.com/9251947/103465650-36584e00-4d3e-11eb-946c-82541233a227.jpg)
![Screenshot_20210102_210428_net wagic app](https://user-images.githubusercontent.com/9251947/103465651-39533e80-4d3e-11eb-8b1e-7c563b6f1ff3.jpg)

**Comment by 3xpFlameS** [comment]
Does that suffice?

**Comment by Vitty85** [comment]
Actually not, which deck.txt are you using ? Can you send me?

Also can you try to play in English? Just to be sure it’s not depending on German Lang.

See you.

--
Inviato da iPhone
