### ISSUE TITLE
Stormsurge kraken

### ISSUE THREAD

**Issue by ranger7271** [WagicProject/wagic#1049]
Lieutenant ability is not working

**Comment by Vitty85** [comment]
You are right, this is the correct version:

`[card]`
`name=Stormsurge Kraken`
`abilities=opponentshroud`
`auto=aslongas(*[iscommander]|mybattlefield) 2/2 >0`
`auto=@combat(blocked) source(this) restriction{type(*[iscommander]|myBattlefield)~morethan~0}:may name(Draw 2 cards) draw:2 controller`
`text=Hexproof -- Lieutenant — As long as you control your commander, Stormsurge Kraken gets +2/+2 and has "Whenever Stormsurge Kraken becomes blocked, you may draw two cards."`
`mana={3}{U}{U}`
`type=Creature`
`subtype=Kraken`
`power=5`
`toughness=5`
`[/card]`

I will include this fix in the next version.

**Comment by Vitty85** [comment]
Closed with new release available on official release links.
