### ISSUE TITLE
Card issues

### ISSUE THREAD

**Issue by ranger7271** [WagicProject/wagic#1050]
Corsair captain - not giving+1/+1 to pirates

Vanquisher banner does not ask for a creature type. Gives bonus to every creature.

**Comment by Vitty85** [comment]
You are right, these are the correct versions:

`[card]`
`name=Corsair Captain`
`auto=token(Treasure Sur)`
`auto=lord(other creature[pirate]|mybattlefield) 1/1`
`text=When Corsair Captain enters the battlefield, create a Treasure token. (It's an artifact with " {T}, Sacrifice this artifact: Add one mana of any color.") -- Other Pirates you control get +1/+1.`
`mana={2}{U}`
`type=Creature`
`subtype=Human Pirate`
`power=2`
`toughness=2`
`[/card]`

`[card]`
`name=Vanquisher's Banner`
`auto=chooseatype all(this) transforms((,newability[lord(creature[chosentype]|mybattlefield) 1/1],newability[@movedTo(creature[chosentype]|mystack):draw:1 controller])) forever chooseend`
`text=As Vanquisher's Banner enters the battlefield, choose a creature type. -- Creatures you control of the chosen type get +1/+1. -- Whenever you cast a creature spell of the chosen type, draw a card.`
`mana={5}`
`type=Artifact`
`[/card]`

I will include these fix in the next version.

**Comment by Vitty85** [comment]
Closed with new release available on official release links.
