### ISSUE TITLE
Etchings of the chosen

### ISSUE THREAD

**Issue by ranger7271** [WagicProject/wagic#1051]
I'm not sure this card is working correctly

**Comment by Vitty85** [comment]
You are right, this is the correct version:

`[card]`
`name=Etchings of the Chosen`
`auto=chooseatype transforms((,newability[lord(creature[chosentype]|mybattlefield) 1/1],newability[{1}{S(creature[chosentype]|mybattlefield)}:name(Creature gains indestructible) target(creature) indestructible ueot])) chooseend`
`text=As Etchings of the Chosen enters the battlefield, choose a creature type. -- Creatures you control of the chosen type get +1/+1. -- {1}, Sacrifice a creature of the chosen type: Target creature you control gains indestructible until end of turn.`
`mana={1}{W}{B}`
`type=Enchantment`
`[/card]`

I will include this fix in next release, see you soon.

**Comment by Vitty85** [comment]
Closed with new release available on official release links.
