### ISSUE TITLE
  Gishath Sun's avatar

### ISSUE THREAD

**Issue by ranger7271** [WagicProject/wagic#1052]
Ability not working

**Comment by Vitty85** [comment]
You are right, this is the correct version:

`[card]`
`name=Gishath, Sun's Avatar`
`abilities=vigilance,trample,haste`
`auto=@combatdamaged(player) from(this):name(Reveal cards) reveal:thatmuch optionone name(Get dinosaurs) target(<anyamount>creature[dinosaur]|reveal) moveto(mybattlefield) optiononeend optiontwo name(put on bottom) target(*|reveal) bottomoflibrary and!( all(*|reveal) bottomoflibrary )! optiontwoend revealend`
`text=Trample, vigilance, haste -- Whenever Gishath, Sun's Avatar deals combat damage to a player, reveal that many cards from the top of your library. Put any number of Dinosaur creature cards from among them onto the battlefield and the rest on the bottom of your library in a random order.`
`mana={5}{R}{G}{W}`
`type=Legendary Creature`
`subtype=Dinosaur Avatar`
`power=7`
`toughness=6`
`[/card]`

i will add this fix in next version, see you.

**Comment by Vitty85** [comment]
Closed with new release available on official release links.
