### ISSUE TITLE
Sunforger

### ISSUE THREAD

**Issue by ranger7271** [WagicProject/wagic#1053]
Ability not working

**Comment by Vitty85** [comment]
This time you are wrong.

This is the correct way to activate ability:

1)Add white and red to your manapool
2)Click on equipped creature
3)Search your library for a white or red instant with manacost 4 or less
4)The game will cast the instant.

I tested and it's working fine.

**Comment by ranger7271** [comment]
I was clicking on the equipment and not the creature

Thanks
