### ISSUE TITLE
Gargos

### ISSUE THREAD

**Issue by ranger7271** [WagicProject/wagic#1054]
Hydra discount not working

**Comment by Vitty85** [comment]
You are right, this is the correct version:

`[card]`
`name=Gargos, Vicious Watcher`
`abilities=vigilance`
`auto=lord(hydra|mycastingzone) altercost(colorless, -4)`
`auto=@targeted(creature|mybattlefield):transforms((,newability[target(creature|opponentbattlefield) dynamicability<!powerstrike eachother!>]))`
`text=Vigilance -- Hydra spells you cast cost {4} less to cast. -- Whenever a creature you control becomes the target of a spell, Gargos, Vicious Watcher fights up to one target creature you don't control.`
`mana={3}{G}{G}{G}`
`type=Legendary Creature`
`subtype=Hydra`
`power=8`
`toughness=7`
`[/card]`

i will include this fix in next release, see you.

**Comment by Vitty85** [comment]
Closed with new release available on official release links.
