### ISSUE TITLE
How to compile for linux with SDL?

### ISSUE THREAD

**Issue by kelvinhammond** [WagicProject/wagic#1057]
Hello, I'd like to try and help with development a bit or at least look at the project but I'm running into issues compiling this on Linux. 

How do I compile this project on Linux using SDL?
Does SDL still work?

I'd like to add support for joystick controllers and to cross-compile this for ODroidGo-Advance.

I followed this guide for QT https://github.com/WagicProject/wagic/wiki/Compiling

**Comment by Vitty85** [comment]
Hi,

At the moment you can compile for Linux using QT or using the standard make file with X11 support. To compile with standard make (no QT) you have to first compile JGE lib (it has it's own makefile) and then you can compile MTG with it's own make file (make x11).

Actually the X11 version is quite worse than the QT one (no audio, no mouse support, etc.), so i would suggest to use the QT.

Hope it helps, see you.

**Comment by kelvinhammond** [comment]
OK thank you, closing this issue. I'll split this into other issues.
