### ISSUE TITLE
Controller support on QT

### ISSUE THREAD

**Issue by kelvinhammond** [WagicProject/wagic#1058]
Hello,

I have a joypad / controller. Is there a way to add support for controllers? I'm unable to bind the joystick to keypads on QT.

**Comment by Vitty85** [comment]
I found this:

https://linuxhint.com/gamepad_mapping_apps_linux/

basically you map your joypad as a keyboard and so it should work for Wagic basic inputs.

let me know, see you.

**Comment by kelvinhammond** [comment]
How do you do this on windows though?

**Comment by Vitty85** [comment]
You can do following this:

https://www.addictivetips.com/windows-tips/map-controller-to-keyboard/

**Comment by kelvinhammond** [comment]
@Vitty85 I tried this with antimicro, I'm not sure what the correct mappings should be if I'm using a controller. Do you know which keyboard keys would map to which psp buttons?

**Comment by Vitty85** [comment]
Check the button on key mapping in game settings, you can easily understand which key you should map.

**Comment by Vitty85** [comment]
> @Vitty85 I tried this with antimicro, I'm not sure what the correct mappings should be if I'm using a controller. Do you know which keyboard keys would map to which psp buttons?

Hi,

Generally you can always check the button on key mapping in game settings, you can easily understand which key you should map and choose the mapping you prefer. By the way, to make it similar to PSP i recommend this mapping:

Q->L1
E->R1
I->Triangle
K->X
J->Square
Space->Circle
Esc/Return->Start
Left Ctrl.->Select
Up->Up
Down->Down
Left->Left
Right->Right

I hope it helps, see you.

**Comment by kelvinhammond** [comment]
Thanks, I got it to work, here is the antimicro file I used [wagic.gamecontroller.amgp.txt](https://github.com/WagicProject/wagic/files/7025811/wagic.gamecontroller.amgp.txt)
