### ISSUE TITLE
Card Image Downloader issue

### ISSUE THREAD

**Issue by DoidArthas** [WagicProject/wagic#1062]
In the README file for the card downloader, it points to a place or to archives that don't even exists in the JRE or JDK directorys, and the replacement files doesn't seems to work
The downloader presents this error:
Warning: Problem fetching card: Ancestor's Chosen (130550.jpg) from https://img.scryfall.com/cards/large/front/7/a/7a5cd03c-4227-4551-aa4b-7d119f0468b5.jpg?1562550217, i will try with slow method...
Error: Problem saving card: Ancestor's Chosen (130550.jpg), i will not download it...

**Comment by Vitty85** [comment]
Hi, Which version of JAVA are you using?

With JDK 1.8 there is no problem, i just used right now.

The security policy files have to be replaced in the folder i said for JAVA 1.8, i don't know if it's same for other version of JAVA.

**Comment by DoidArthas** [comment]
Using windows and JDK 8 (1.8.0_301)
![sec](https://user-images.githubusercontent.com/54484378/126902094-3f038d6b-f555-44fd-8c9c-5c2610633cc7.PNG)
Security folder is like that, and in the policy folder there is  2 folders, "limited" and "unlimited", in both folders, there is files, "local_policy" and "US_export_policy", but replacing them doesn't work

**Comment by Vitty85** [comment]
Copy in security folder as they are, not in policy.

Il Dom 25 Lug 2021, 16:12 Neemias ***@***.***> ha scritto:

**Comment by DoidArthas** [comment]
Same error

**Comment by Vitty85** [comment]
Are you sure you have just one java installation?
when you run jar application, which java is starting?

**Comment by Vitty85** [comment]
Also, in your wagic/user folder is there already the empty set folder right?

**Comment by Vitty85** [comment]
It's important that the User folder is existing and also sets folder too, so firstly start Wagic at least one time and then use the downloader.

**Comment by DoidArthas** [comment]
Yes, i have one single installation, but it creates 2 folders, one for JDK and one for JRE, i've just copied to all lib/security folders and it seems to work now. 
Thank you, it's already downloading
