### ISSUE TITLE
Werewolf's Issues

### ISSUE THREAD

**Issue by DoidArthas** [WagicProject/wagic#1064]
I can't find the card Moonmist in the editor, guess its missing

**Comment by DoidArthas** [comment]
And the rule for transforming werewolfs are valid for each player separated, if both players plays 2 spells, the werewolf doesnt transform. One single player must cast 2 or more spells for that

**Comment by DoidArthas** [comment]
Basically, the game is considering all the cards cast this turn, instead to the cards played by each player

**Comment by DoidArthas** [comment]
The Effect of "Vildin-Pack Alpha" is not triggering too

**Comment by DoidArthas** [comment]
For some reason, "Moonrise Intruder" dont transform in the next turn, even if I cast 2 spells

**Comment by EduardoMunozGomez** [comment]
Can confirm this bug, to be clear each player casting one spell is no condition for the werewolves to transform, a single player must cast two or more spells.

Thank you for reporting.

**Comment by Vitty85** [comment]
From Gathrerer rules:

To trigger the Werewolf’s back face’s transform ability, a single player must have cast two or more spells during the previous turn. If multiple players each cast just one spell during the previous turn, the ability won’t trigger.

**Comment by Vitty85** [comment]
Hi,

I did some tests and it seems all ok.

Can you please test this new core zip file with my modifications?
https://github.com/Vitty85/wagic/releases/download/travis-ci/Wagic-core-0231.zip

Thanks.

**Comment by DoidArthas** [comment]
I will test now

**Comment by DoidArthas** [comment]
Vildin-Pack Alpha is triggering properly

**Comment by DoidArthas** [comment]
Moonmist is available, and the effect is done well, but if I cast something, and cast Moonmist after, the werewolfs transformed by Moonmist dont transform back in the next upkeep (I've casted 2 spells this turn)

**Comment by DoidArthas** [comment]
In fact, the never transform back anymore after Moonmist

**Comment by DoidArthas** [comment]
Moonrise Intruder seems to be working now

**Comment by DoidArthas** [comment]
I dont know if the werewolf transformed by the effect of Vildin-Pack Alpha dont transform back like Moonmist effect, but there's a chance

**Comment by Vitty85** [comment]
Hi, I guess I didn’t understand the issue with the transformation of moonmist and Vildin.

Can you make an example with a combo of cards?

--
Inviato da iPhone

**Comment by DoidArthas** [comment]
Sorry,

**Comment by Vitty85** [comment]
Don't forget that Moonmist has effect only when creature is Human, and also the wayback transformation triggers when you cast no spell, not when you cast 2 spell.

**Comment by DoidArthas** [comment]
I was with 7 humans in the field, including Vidil, then I've cast one human, and after this, in combat I've cast moonmist. They transformed. In this turn, I've casted 2 spells, the werewolfs should transform back, but this didn't happened

**Comment by Vitty85** [comment]
I did same test and it worked.... Do you remember the cards on battlefield? Can you test again with the core file i said you?

**Comment by DoidArthas** [comment]
I dont remember, will test again and tell you,
Im using your core

**Comment by Vitty85** [comment]
This one right? https://github.com/WagicProject/wagic/releases/download/wagic-v0.23.1/Wagic-core-0231.zip

Thanks.

**Comment by DoidArthas** [comment]
Its strange, the bug dont occur anymore. Well, if occur again, I reopen the issue
Thank You!
