### ISSUE TITLE
Pacifism

### ISSUE THREAD

**Issue by DoidArthas** [WagicProject/wagic#1065]
Going back to the werewolves, I had a "Reckless Waif" on the battlefield, and my opponent made a pacifism on the card, after that, the ability triggered and the card transformed. Now I can attack with it, even with the pacifism on it

**Comment by Vitty85** [comment]
This sound a bit more complicated to solve, I presume all the dual face cards can have same issue… just for question, if you transform one more time to the original creature of pacisifm, does it attack?

**Comment by DoidArthas** [comment]
I dont know, will test soon

**Comment by Vitty85** [comment]
I saw and at the moment it's almost impossible to solve this issue, basically the transformations is erasing the auras effect on abilities and i couldn't solve without a huge impact on engine, sorry.

**Comment by Vitty85** [comment]
Maybe not so impossible, i guess i could find an easy way, let's see.

**Comment by Vitty85** [comment]
You can test the new release: https://github.com/WagicProject/wagic/releases/tag/wagic-v0.23.1

Le me know if it's ok.

**Comment by DoidArthas** [comment]
Ok

**Comment by DoidArthas** [comment]
Tested and its working
