### ISSUE TITLE
Changelog file is not updated

### ISSUE THREAD

**Issue by remigiusz-suwalski** [WagicProject/wagic#1067]
https://github.com/WagicProject/wagic/tags shows only one tag released in last two years, wagic-v0.23.1. It looks like this tag is constantly moving, following HEAD of master which contradicts https://semver.org/

> Once a versioned package has been released, the contents of that version MUST NOT be modified. Any modifications MUST be released as a new version.

Can we keep the tags frozen? And where is the most up-to-date version of the Changelog file?

**Comment by Vitty85** [comment]
Hi,

For next major release i will try to keep in mind....

Actually i'm almost alone to work on this repo, so i'm doing my best.

I don't have a changelog file, the main features i added are are described in the comment of release and in the official forum of Wagic.

See you.

**Comment by Vitty85** [comment]
Hi,

I updated changelog with last 3 years of modifications, I hope this is helpful.

I will try to keep it up to date even in future releases, see you soon.
