### ISSUE TITLE
Windows 10 WagicWindows-0231 opens then closes immediately

### ISSUE THREAD

**Issue by soltaker21** [WagicProject/wagic#1069]
I'm having issues running the windows version of the latest release WagicWindows-0231 on Windows 10 Home 64 bit 20H2 19042.1165 
Upon double clicking on Wagic.exe I see a small circle on my mouse indicating its loading something and then I see nothing. It does appear in my task manager for a moment before just immediately closing. I see no error message and it doesn't create any crash file or log dump within the wagic folder. I have managed to spot that it will open WerFault.exe in the details list of the task manager as well. So I checked through windows event viewer and found this as a possible cause:

Faulting application name: Wagic.exe, version: 0.0.0.0, time stamp: 0x613e36cb
Faulting module name: ntdll.dll, version: 10.0.19041.1110, time stamp: 0x8a32a22a
Exception code: 0xc0000005
Fault offset: 0x0004786e
Faulting process id: 0x2564
Faulting application start time: 0x01d7a8620a50f514
Faulting application path: H:\Wagic\Wagic.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll

I have scoured old forum posts and github issues listings here but nothing presented has seemed to work. I have uninstalled/reinstalled both 64 bit (vcredist_x64) and 32 bit (vcredist_x86) versions for Visual C++ 2010 I have tried it with one installed but not the other as well restarting between each attempt. I ran DISM and sfc in windows cmd to be sure of the integrity of system files. I have also tried previous Wagic windows releases but they exhibit the same behavior.
I have tried running as admin and all compatibility mode options but the same behavior persists.

**Comment by Flounder1664** [comment]
I have the same issue on Windows 10 Pro for 231, after similar C++ trouble shooting.

**Comment by Vitty85** [comment]
Hi,

I tested all the versions before release... i downloaded the zip in 2 different PC with Windows 10 and the game run without any problem... I guess you have something wrong with your PC.

Download again now and retry, i don't what's wrong on your PC, but it's not up to game.

**Comment by soltaker21** [comment]
I found the issue thank you for a picture of your environment.
I had all of the Visual C++ Redistributables you have but I did not have Microsoft Visual J# 2.0 Redistributable Package. After installation of that Wagic started up with no issues.

Would it be possible to include Visual J# 2.0 as a requirement listing in the Readme.md file to assist others if they have this issue?

**Comment by Vitty85** [comment]
I'm happy you solved.

Actually i'm not sure the README is the correct place, i will think about a solution, maybe a section in the Wiki of Wagic GitHub.

See you.
