### ISSUE TITLE
No way to back out of store menu

### ISSUE THREAD

**Issue by ruralTom** [WagicProject/wagic#1076]
There's no cancel button. I use a Motorola G5+ with finger print motions instead of a navigation bar and that might be the issue.

Left swipe is back for me and right swipe is the recents menu and a single tap to go home.

Pulling up the recents menu works, tapping to go back to my home screen works. Trying to go back to the menu is a no-go.

I included a photo of the screen I am referring to. ![](https://i.imgur.com/9Ebz2kL.jpg)

**Comment by Vitty85** [comment]
Hi, try to slide from down to up, the gesture is that on Wagic for Android.

**Comment by Antaritic** [comment]
您好！邮件已收到，我将尽快回复。

此致
      祝好
