### ISSUE TITLE
android apk serves outdated zip from server

### ISSUE THREAD

**Issue by GnomeBeans** [WagicProject/wagic#1084]
**Describe the bug**
the latest apk under releases downloads .23.1 zip after giving it permissions. This happens on my google pixel

**To Reproduce**
Get apk. run and give file permissions. When selecting where to install it grabs an outdated version from server

**Expected behavior**
expecting 23.2 because that was the header for the asset I downloaded

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
google pixel 

**Additional context**
how do I perform the back button on a touchscreen? Does this game require a controller to play?

**Comment by Flavor821** [comment]
> **Describe the bug**
> the latest apk under releases downloads .23.1 zip after giving it permissions. This happens on my google pixel
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> Get apk. run and give file permissions. When selecting where to install it grabs an outdated version from server
> 
> **Expected behavior**
> expecting 23.2 because that was the header for the asset I downloaded
> 
> **Screenshots**
> n/a
> 
> **Desktop (please complete the following information):**
> n/a
> 
> **Smartphone (please complete the following information):**
> google pixel 
> 
> **Additional context**
> how do I perform the back button on a touchscreen? Does this game require a controller to play?
> 

Same issue here no back button Google Pixel

**Comment by Flavor821** [comment]
> **Describe the bug**
> the latest apk under releases downloads .23.1 zip after giving it permissions. This happens on my google pixel
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> Get apk. run and give file permissions. When selecting where to install it grabs an outdated version from server
> 
> **Expected behavior**
> expecting 23.2 because that was the header for the asset I downloaded
> 
> **Screenshots**
> n/a
> 
> **Desktop (please complete the following information):**
> n/a
> 
> **Smartphone (please complete the following information):**
> google pixel 
> 
> **Additional context**
> how do I perform the back button on a touchscreen? Does this game require a controller to play?
> 

@GnomeBeans easy Fix on Google Fones - need to change Gestures to 3 points in Settings-System - Gesture and the normal Android 3 Button point will show

**Comment by GnomeBeans** [comment]
@Flavor821 that fixed the controls.

The only issue I have left is 23.1 works but the apk for 24 says package appears to be invalid.

**Comment by GnomeBeans** [comment]
I'm closing this issue since the issue with 24 is a new issue.
