### ISSUE TITLE
.24 apk appears to be invalid

### ISSUE THREAD

**Issue by GnomeBeans** [WagicProject/wagic#1086]
**Describe the bug**

Running .24 gives error "apk appears to be invalid"

**To Reproduce**
Run apk

**Expected behavior**

The app would launch the way .23 does

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 Google pixel 6 pro
 android 13
 firefox with permissions. google drive with permissions

**Additional context**
![Screenshot (Apr 23, 2023 12 27 24 PM)](https://user-images.githubusercontent.com/53883426/233858167-e6b5adcf-4267-4ae4-b520-cd8062c8579d.png)

**Comment by Vitty85** [comment]
Strange, i will recompile with a lower SDK and re-upload ASAP.

**Comment by Vitty85** [comment]
New APK compiled with SDK version 29 has been updated in 0.24.0 release, it has been tested on Galaxy A52 with Andorid 13 version and it seems ok.

Let me know, see you.
