### ISSUE TITLE
Problem with Colorless mana ability filter and auto={T}:Add{c}

### ISSUE THREAD

**Issue by EduardoMunozGomez** [WagicProject/wagic#1090]
**Describe the bug**
In Deck Editor -> Add filter -> Mana Ability -> Select Colorless mana ability and apply the filter
It shows cards with the code auto={T}:Add{1} but it doesn't show newer cards that are coded with auto={T}:Add{c}

So cards like the following are not included in the filter:

[card]
name=Animal Sanctuary
**auto={T}:add{C}**
auto={2}{T}:counter(1/1) target(creature[bird;cat;dog;goat;ox;snake])
text={T}: Add {C}. -- {2}, {T}: Put a +1/+1 counter on target Bird, Cat, Dog, Goat, Ox, or Snake.
type=Land
[/card]

**Comment by Vitty85** [comment]
I will take a look.

**Comment by Vitty85** [comment]
I solved in WFilter.cpp, now the filter consider {c} and {1} as the same by an inline chars replace during match of mana colors

**Comment by Vitty85** [comment]
Solved with last commit.
