### ISSUE TITLE
Cards not adding to collection

### ISSUE THREAD

**Issue by GlitchHunter00** [WagicProject/wagic#1091]
**Describe the bug**
Certain cards will not appear in collection

**To Reproduce**
open collection.dat
 paste the following card ID's
555398
430427
554229
563188
563196
563220

only 2 of these will appear in the collection. 563220 (Sky Diamond) and 570318 (Fire Diamond)

**Expected behavior**
The following cards should be in the collection:
Lord Xander, the Collector (SNC)
Assault Suit (CMA)
Bonehoard (NEC)
Charcoal Diamond (CLB)
Fire Diamond (CLB)
Sky Diamond (CLB)

**Screenshots**
https://i.imgur.com/G24Dm4G.png
https://i.imgur.com/wNfxGA2.png

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 0.24.0

Other info
I was trying to recreate an adjustment to a physical commander deck for playtesting in Wagic, but can't since some of the cards from the start were not importing into the collection correctly.

**Comment by Antaritic** [comment]
您好！邮件已收到，我将尽快回复。

此致
      祝好

**Comment by Vitty85** [comment]
Some of these cards are unsupported... did you check if they are in unsupported.txt file? or if they are in MissingCardList.txt?

It's not a bug, simply this card are not implemented in Wagic.

See you.

**Comment by GlitchHunter00** [comment]
tried again, no filters, no trailing characters, just 7ED printing of Charcoal diamond.

Absolutely nothing. Thanks anyways.

**Comment by Vitty85** [comment]
ok,

Download again the core file from latest release. and try this collection.dat (i zipped to make it smaller):

[collection.zip](https://github.com/WagicProject/wagic/files/11735659/collection.zip)

Let me know.

**Comment by GlitchHunter00** [comment]
> ok,
> 
> Download again the core file from latest release (replace it in your Res folder), and try this collection.dat (i zipped to make it smaller):
> 
> [collection.zip](https://github.com/WagicProject/wagic/files/11735659/collection.zip)
> 
> Let me know.
I Reinstalled core, and am using the attached collection
Only filter used is "First letter C" for this.
https://i.imgur.com/OaEhZqQ.png
Collection goes straight from Chapel Shieldgeist to Charge Through.

**Comment by Vitty85** [comment]
Hi again,

Filter first for set CLB (Commander Legends: Battle for Baldur's Gate) and then add filter for letter C, it will make the search easier. 

Also, the filters i meant are not the filter in the menu, but the filters you can set from the grid view by using the mouse scroll, be sure you are seeing the whole collection list and not just a specific type of cards.

I'm using same dat and same version (if you downloaded the latest release today) and i can see the Charcoal Diamond in Commander Legends: Battle for Baldur's Gate SET.

Hope you can solve with this, see you.

**Comment by EduardoMunozGomez** [comment]
I belive you can't just paste the id of a card in the collection file and make that appear, its by design you can't just edit the collection.dat.
