### ISSUE TITLE
Can we block/ban user Antaritic due to spam?

### ISSUE THREAD

**Issue by Darthagnon** [WagicProject/wagic#1093]
> 您好！邮件已收到，我将尽快回复。
>
> 此致
>     祝好
>
> _Originally posted by @Antaritic in https://github.com/WagicProject/wagic/issues/1092#issuecomment-1616015780_

Can the WagicProject heads [ban or block](https://docs.github.com/en/communities/maintaining-your-safety-on-github/blocking-a-user-from-your-organization) user @Antaritic? Every issue or pull request is spammed with a read receipt by an email response bot under his username, and he has not been active since 2017, and the spam creates unecessary noise in an already issue- and legacy-heavy project.

**Comment by Vitty85** [comment]
Since I’m not admin in Wagic I cannot directly block him/it but at least I issued a ticket on GitHub in order to disallow him to post content here, I hope it will work.

Thanks for your report.
