### ISSUE TITLE
Wagic Sample Round video was gone (now restored)

### ISSUE THREAD

**Issue by Darthagnon** [WagicProject/wagic#1095]
I reached out to Rolz73, who recorded the Wagic sample round video in the Readme. 

Rolz73 replied (2AM GMT 26/02/2024): "oh hi. I still have all my old videos, but privated a bunch just so that it was more consistent with my latest vids. Twitch related. That's all."

The video has been restored (unlisted) to https://www.youtube.com/watch?v=WUFSAPZuDIk ([archive.today](https://archive.today/9SuTj), [archive.org](https://web.archive.org/web/20240226201245/https://www.youtube.com/watch?v=WUFSAPZuDIk))

**Comment by Antaritic** [comment]
您好！邮件已收到，我将尽快回复。

此致
      祝好
