### ISSUE TITLE
CardImageLinks.csv has 124 broken URLs

### ISSUE THREAD

**Issue by GnomeBeans** [WagicProject/wagic#1099]
PLIST front card URLs are broke. The rest can't find the /back/ version of the card which results in no card in the zip at all even if the front card URL is reachable.

Currently downloading images for: OTP
Cannot retrieve image url for card: Crime (658275)

Currently downloading images for: MKM
Cannot retrieve image url for card: Kellan, Inquisitive Prodigy (649885)
Cannot retrieve image url for card: Kellan, Inquisitive Prodigy (646768)
Cannot retrieve image url for card: Hustle (646803)
Cannot retrieve image url for card: Fuss (646802)
Cannot retrieve image url for card: Flotsam (646801)
Cannot retrieve image url for card: Cease (646800)
Cannot retrieve image url for card: Push (646804)

Currently downloading images for: PLIST
Cannot retrieve image url for card: Scourge of the Throne (295350)
Cannot retrieve image url for card: Emeria, the Sky Ruin (295486)
Cannot retrieve image url for card: Fabricate (295257)
Cannot retrieve image url for card: Helix Pinnacle (295374)
Cannot retrieve image url for card: Memnite (295461)
Cannot retrieve image url for card: Swiftfoot Boots (295470)
Cannot retrieve image url for card: Boros Challenger (295400)
Cannot retrieve image url for card: Maelstrom Nexus (295417)
Cannot retrieve image url for card: Living Death (295302)

Currently downloading images for: OTC
Cannot retrieve image url for card: Heaven (658674)

Currently downloading images for: RVR
Cannot retrieve image url for card: Find (643252)
Cannot retrieve image url for card: Thrash (643253)
Cannot retrieve image url for card: Expansion (643250)
Cannot retrieve image url for card: Bedeck (643251)
Cannot retrieve image url for card: Repudiate (643256)
Cannot retrieve image url for card: Response (643254)
Cannot retrieve image url for card: Assure (643255)
Cannot retrieve image url for card: Connive (643249)
Cannot retrieve image url for card: Warrant (643247)
Cannot retrieve image url for card: Revival (643248)

Currently downloading images for: LCC
Cannot retrieve image url for card: Commit (640443)
Cannot retrieve image url for card: Promise of Aclazotz (640276)
Cannot retrieve image url for card: Promise of Aclazotz (640044)

Currently downloading images for: LCI
Cannot retrieve image url for card: Kellan, Daring Traveler (639268)
Cannot retrieve image url for card: Kellan, Daring Traveler (636951)

Currently downloading images for: MB1
Cannot retrieve image url for card: Dolmen Gate (294557)
Cannot retrieve image url for card: Herald's Horn (294577)
Cannot retrieve image url for card: Ancient Den (294636)
Cannot retrieve image url for card: Arch of Orazca (294639)
Cannot retrieve image url for card: Umbral Mantle (294630)
Cannot retrieve image url for card: Priest of Titania (294283)
Cannot retrieve image url for card: Bladewing the Risen (294384)
Cannot retrieve image url for card: Cunning Breezedancer (294397)
Cannot retrieve image url for card: Tireless Tracker (294345)

Currently downloading images for: M3C
Cannot retrieve image url for card: Find (665675)

Currently downloading images for: SPG
Cannot retrieve image url for card: Brazen Borrower (660838)

Currently downloading images for: MKC
Cannot retrieve image url for card: Dusk (650155)
Cannot retrieve image url for card: Connive (650297)
Cannot retrieve image url for card: Discovery (650301)

Currently downloading images for: WOE
Cannot retrieve image url for card: Kellan, the Fae-Blooded (631710)
Cannot retrieve image url for card: Minecart Daredevil (629642)
Cannot retrieve image url for card: Ratcatcher Trainee (629645)
Cannot retrieve image url for card: Two-Headed Hunter (629656)
Cannot retrieve image url for card: Virtue of Courage (629658)
Cannot retrieve image url for card: Virtue of Loyalty (629539)
Cannot retrieve image url for card: Beanstalk Wurm (629662)
Cannot retrieve image url for card: Aquatic Alchemist (629541)
Cannot retrieve image url for card: Beluna's Gatekeeper (629544)
Cannot retrieve image url for card: Bramble Familiar (629665)
Cannot retrieve image url for card: Ferocious Werefox (629671)
Cannot retrieve image url for card: Galvanic Giant (629553)
Cannot retrieve image url for card: Hollow Scavenger (629675)
Cannot retrieve image url for card: Horned Loch-Whale (629554)
Cannot retrieve image url for card: Obyra's Attendants (629564)
Cannot retrieve image url for card: Picklock Prankster (629565)
Cannot retrieve image url for card: Stormkeld Vanguard (629688)
Cannot retrieve image url for card: Vantress Transmuter (629576)
Cannot retrieve image url for card: Virtue of Knowledge (629577)
Cannot retrieve image url for card: Virtue of Strength (629698)
Cannot retrieve image url for card: Conceited Witch (629585)
Cannot retrieve image url for card: Fell Horseman (629593)
Cannot retrieve image url for card: Gumdrop Poisoner (629594)
Cannot retrieve image url for card: Beluna Grandsquall (629721)
Cannot retrieve image url for card: Cruel Somnophage (629723)
Cannot retrieve image url for card: Callous Sell-Sword (629722)
Cannot retrieve image url for card: Devouring Sugarmaw (629725)
Cannot retrieve image url for card: Decadent Dragon (629724)
Cannot retrieve image url for card: Frolicking Familiar (629727)
Cannot retrieve image url for card: Elusive Otter (629726)
Cannot retrieve image url for card: Heartflame Duelist (629729)
Cannot retrieve image url for card: Gingerbread Hunter (629728)
Cannot retrieve image url for card: Imodane's Recruiter (629730)
Cannot retrieve image url for card: Mosswood Dreadknight (629732)
Cannot retrieve image url for card: Kellan, the Fae-Blooded (629731)
Cannot retrieve image url for card: Pollen-Shield Hare (629734)
Cannot retrieve image url for card: Picnic Ruiner (629733)
Cannot retrieve image url for card: Scalding Viper (629736)
Cannot retrieve image url for card: Questing Druid (629735)
Cannot retrieve image url for card: Spellscorn Coven (629738)
Cannot retrieve image url for card: Virtue of Persistence (629616)
Cannot retrieve image url for card: Shrouded Shepherd (629737)
Cannot retrieve image url for card: Tempest Hart (629739)
Cannot retrieve image url for card: Twining Twins (629741)
Cannot retrieve image url for card: Threadbind Clique (629740)
Cannot retrieve image url for card: Bellowing Bruiser (629622)
Cannot retrieve image url for card: Woodland Acolyte (629742)
Cannot retrieve image url for card: Besotted Knight (629505)
Cannot retrieve image url for card: Cheeky House-Mouse (629508)
Cannot retrieve image url for card: Grabby Giant (629634)
Cannot retrieve image url for card: Hearth Elemental (629637)
Cannot retrieve image url for card: Twining Twins (632248)
Cannot retrieve image url for card: Scalding Viper (632247)
Cannot retrieve image url for card: Intrepid Trufflesnout (632081)
Cannot retrieve image url for card: Virtue of Loyalty (632229)
Cannot retrieve image url for card: Virtue of Knowledge (632231)
Cannot retrieve image url for card: Horned Loch-Whale (632230)
Cannot retrieve image url for card: Bramble Familiar (632235)
Cannot retrieve image url for card: Virtue of Courage (632234)
Cannot retrieve image url for card: Virtue of Persistence (632233)
Cannot retrieve image url for card: Gumdrop Poisoner (632232)
Cannot retrieve image url for card: Decadent Dragon (632239)
Cannot retrieve image url for card: Cruel Somnophage (632238)
Cannot retrieve image url for card: Beluna Grandsquall (632237)
Cannot retrieve image url for card: Virtue of Strength (632236)
Cannot retrieve image url for card: Heartflame Duelist (632242)
Cannot retrieve image url for card: Elusive Otter (632241)
Cannot retrieve image url for card: Devouring Sugarmaw (632240)
Cannot retrieve image url for card: Questing Druid (632246)
Cannot retrieve image url for card: Pollen-Shield Hare (632245)
Cannot retrieve image url for card: Mosswood Dreadknight (632244)
Cannot retrieve image url for card: Kellan, the Fae-Blooded (632243)

Currently downloading images for: CLU
Cannot retrieve image url for card: Discovery (651922)
Cannot retrieve image url for card: Depose (651920)
Cannot retrieve image url for card: Status (651945)
Cannot retrieve image url for card: Integrity (651933)
Cannot retrieve image url for card: Incubation (651932)

**Comment by GnomeBeans** [comment]
[comprehensive log.txt](https://github.com/user-attachments/files/16501604/comprehensive.log.txt)

**Comment by GnomeBeans** [comment]
I notice that these are almost all back cards with the exception of PLIST

**Comment by GnomeBeans** [comment]
I've also observed that there are no errors mentioning /front/ only /back/ even still the front card doesn't exist in the zip even though the front is accessible. Not sure how you're handling double sided cards but it isn't saving front when back is not found so you would end up without the card at all which makes the collection incomplete.

**Comment by EduardoMunozGomez** [comment]
Thank you for bringing this to my attention. I had to modify how the _cards.dat files are created to incorporate variant layouts of adventures, aftermath, and split cards. They are now showing in the collection, but you will need to download the images again.

Some sets like PLST and MB1 don't use an official multiverseID. I'm trying to avoid sets without this identifier for cards. I'm unsure what to do with them, as most are reprints and I believe no new images are present, only the same card with the planeswalker symbol in the lower left corner. Perhaps removing them would be best.

These changes will be included in the next release. I'm currently working on Bloomburrow.

**Comment by GnomeBeans** [comment]
Thanks so much. I'm new to the game and have limited knowledge so I can't recommend anything on those. Except I did find a backup of PLST from elsewhere. No MB1 I guess since its newer.
