### ISSUE TITLE
(graphical glitch) wood / gold textures

### ISSUE THREAD

**Issue by xawotihs** [WagicProject/wagic#461]
_From [wagic.the.homebrew@gmail.com](https://code.google.com/u/wagic.the.homebrew@gmail.com/) on January 11, 2010 04:48:09_

in the Theme Final Saga, the wood and gold textures are empty files, but
the engine shows a thin white line when displaying them.
Erasing the files would solve this,but causes inconsistency with the way we
deal with themes so far.

_Original issue: http://code.google.com/p/wagic/issues/detail?id=293_

**Comment by kevlahnota** [comment]
the current wagic don't use wood and gold textures anymore... see: https://github.com/WagicProject/wagic/pull/641/commits/4c86cae7fe630e026d17ed23c8f29e4c62ebdfc0
