### ISSUE TITLE
Giving card C protection from X does not remove cards attached to C which have quality X

### ISSUE THREAD

**Issue by xawotihs** [WagicProject/wagic#464]
_From [Psyyri...@gmail.com](https://code.google.com/u/100660336188393756016/) on February 18, 2010 22:13:56_

Issue reported in the forum: http://wololo.net/forum/viewtopic.php?f=13&t=1186 Auras and Enchantments attached to a card should be 
removed when their target gains protection from a 
quality which they have. This is not the case 
though. For reference, the respective rules:

702.14c A permanent or player with protection can't 
be enchanted by Auras that have the stated quality. 
Such Auras attached to the permanent or player with 
protection will be put into their owners' 
graveyards as a state-based action. (See rule 704, 
"State-Based Actions.")

702.14d A permanent with protection can't be 
equipped by Equipment that have the stated quality 
or fortified by Fortifications that have the stated 
quality. Such Equipment or Fortifications become 
unattached from that permanent as a state-based 
action, but remain on the battlefield. (See rule 
704, "State-Based Actions.")

_Original issue: http://code.google.com/p/wagic/issues/detail?id=352_

**Comment by kevlahnota** [comment]
this is fixed. see: https://github.com/WagicProject/wagic/commit/a6ec3e0a68309ef00079720a1918f81b50b93bc8
