### ISSUE TITLE
Profile name at upper left side is not being updated correctly

### ISSUE THREAD

**Issue by xawotihs** [WagicProject/wagic#469]
_From [engr.nic...@gmail.com](https://code.google.com/u/114307886973377803390/) on June 23, 2010 15:03:56_

1- go to options and change profiles
2- notice that the name on upper left screen on the main menu is not updated

_Original issue: http://code.google.com/p/wagic/issues/detail?id=431_

**Comment by kevlahnota** [comment]
fixed: https://github.com/WagicProject/wagic/commit/297206b054d7cbff9f8874aa3f384373148bf8bc
