### ISSUE TITLE
Compiling using libpng-1.4.5 on Linux

### ISSUE THREAD

**Issue by xawotihs** [WagicProject/wagic#478]
_From [g...@kb.ccchl.de](https://code.google.com/u/107035287676363221130/) on February 16, 2011 17:17:05_

I had a few problems compiling with current libpng and case sensitive filesystem. My patch is attached. Tested on:

Gentoo GNU/Linux amd64
libpng-1.4.5
gcc-4.4.4

**Attachment:** [0001-Compile-fixes.patch](http://code.google.com/p/wagic/issues/detail?id=597)

_Original issue: http://code.google.com/p/wagic/issues/detail?id=597_

**Comment by Rolzad73** [comment]
I thing this got fixed in commit 85f66a8fecded1b8d59bd2fd1794aad59ad7d024.
Closing.
