### ISSUE TITLE
Wagic crashes at cleanup step of turn when creature enchanted with Slow Motion was sacrificed.

### ISSUE THREAD

**Issue by xawotihs** [WagicProject/wagic#518]
_From [Dansi...@gmail.com](https://code.google.com/u/102815067982821057984/) on March 28, 2012 18:52:11_

What steps will reproduce the problem? 1. Enchant an opponent's creature with Slow Motion.
2. Wait for opponent to choose not to pay Slow Motion's upkeep cost.
3. Creature is sacrificed, Slow Motion returns to your hand.
4. At end of opponent's current turn, app crashes.

What is the expected output? The game should continue to run.
What do you see instead? The game freezes during opponent's Cleanup step, then after a few moments it crashes out.

What version of the product are you using? On what operating system? Whatever version is current as of 3/25/12 on Android 2.3.5. Please provide any additional information below.

_Original issue: http://code.google.com/p/wagic/issues/detail?id=823_

**Comment by EduardoMunozGomez** [comment]
In Power Taint and in Slow Motion the bug was still present, fixed it by changing the primitive to:
auto=teach(creature) transforms((,newability[cumulativeupcost[{1}] sacrifice])) in Power Taint.
auto=teach(creature) transforms((,newability[upcost[{2}] sacrifice]))  in Slow Motion.
