### ISSUE TITLE
Creatures that gain flying still can't attack with Magus of the Moat in play

### ISSUE THREAD

**Issue by xawotihs** [WagicProject/wagic#526]
_From [bas.keur...@gmail.com](https://code.google.com/u/114653030182063133764/) on May 13, 2012 17:10:04_

What steps will reproduce the problem? 1. One side plays Magus of the Moat
2. Other side plays Pulmonic Sliver 
3. The Sliver player tries to attack What is the expected output? What do you see instead? Expected to be able to attack, but you do not get that option. What version of the product are you using? On what operating system? Both 0.17.1 and 0.18.6 [Win]

_Original issue: http://code.google.com/p/wagic/issues/detail?id=870_

**Comment by kevlahnota** [comment]
fixed #783
