### ISSUE TITLE
Blinking an aura causes freeze

### ISSUE THREAD

**Issue by xawotihs** [WagicProject/wagic#541]
_From [bjorn.sn...@gmail.com](https://code.google.com/u/115971057303630495942/) on March 06, 2013 05:38:23_

What steps will reproduce the problem? 1. Have aura on creature
2. Play card that removes the aura from the game until end of turn
3. Wait until end of turn What is the expected output? What do you see instead? Aura gets destroyed upon reentering from exile What version of the product are you using? On what operating system? 18.6 on linux Please provide any additional information below. The aura was an arrest placed by AI, Glimmerpoint Stag was used to exile it. The process did not crash or give any error, it simply froze.

_Original issue: http://code.google.com/p/wagic/issues/detail?id=941_

**Comment by kevlahnota** [comment]
fixed on latest-master
