### ISSUE TITLE
Miscalculated P/T reduction from lord ability with transforms ability

### ISSUE THREAD

**Issue by xawotihs** [WagicProject/wagic#542]
_From [anthonyc...@gmail.com](https://code.google.com/u/107628029936763816337/) on April 02, 2013 08:18:03_

What steps will reproduce the problem? 1. Cast Turn to Frog to Serra Angel with Crusade in play What is the expected output? What do you see instead? Serra Angel must become a 1/1 blue frog, instead it becomes 0/0 due to Crusade. Removing Crusade in sample test below will be a succesful test.

#Testing Turn to Frog to Serra Angel with Crusade in play.
[INIT]
FIRSTMAIN
[PLAYER1]
inplay:Serra Angel,Crusade
hand:Turn to Frog
manapool:{1}{U}
[PLAYER2]
[DO]
Turn to Frog
Serra Angel
next
next
eot
next
next
next
[ASSERT]
FIRSTMAIN
[PLAYER1]
inplay:*,*
graveyard:Turn to Frog
manapool:{0}
[END] Please use labels and text to provide additional information. Crusade removes a 1/1 to Serra Angel that becomes a 1/1 blue frog since its no longer white making it a 0/0.

_Original issue: http://code.google.com/p/wagic/issues/detail?id=946_

**Comment by kevlahnota** [comment]
Fixed
