### ISSUE TITLE
marble titan erroneously prevents untap of creature

### ISSUE THREAD

**Issue by xawotihs** [WagicProject/wagic#543]
_From [mertensb...@gmail.com](https://code.google.com/u/116148808979954769334/) on April 02, 2013 20:07:03_

What steps will reproduce the problem? 1. play marble titan ( http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=84533 ):
"Creatures with power 3 or greater don't untap during their controllers' untap steps."
2. increase power (and toughness) of a creature with power less than 3 to 3 or more until end of turn
3. tap the creature What is the expected output? What do you see instead? When the creature's power is reduced to less than 3 at the end of turn the creature should untap during the next untap step.
Instead the creature remains tapped.
Even destroying the marble titan does not allow the creature to untap.

After destroying the marble titan other creature are not affected anymore but the tapped creature remains tapped. What version of the product are you using? On what operating system? Version 0.18.6 on Android 4.1.1 Please provide any additional information below. A meekstone artifact ( http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=11398 ) was also in play but I'm fairly confident this problem didn't arise until after the marble titan was played.

_Original issue: http://code.google.com/p/wagic/issues/detail?id=947_

**Comment by kevlahnota** [comment]
Fixed
