### ISSUE TITLE
AI will creates Spark Elemental after combat phase

### ISSUE THREAD

**Issue by xawotihs** [WagicProject/wagic#545]
_From [mertensb...@gmail.com](https://code.google.com/u/116148808979954769334/) on April 02, 2013 20:19:49_

What steps will reproduce the problem? 1. Fight the AI with one of the initial decks containing Spark Elemental What is the expected output? What do you see instead? During some turns the AI will play the Spark Elemental after the combat phase which means it will be destroyed before being of any use. What version of the product are you using? On what operating system? Version 0.18.6 on android 4.1.1 Please provide any additional information below.

_Original issue: http://code.google.com/p/wagic/issues/detail?id=949_

**Comment by kevlahnota** [comment]
fixed in build #951 
 cards with treason will be skipped by AI if the phase is not first main
