### ISSUE TITLE
Clone goes to graveyard before being able to copy anything

### ISSUE THREAD

**Issue by xawotihs** [WagicProject/wagic#546]
_From [wagic.the.homebrew@gmail.com](https://code.google.com/u/wagic.the.homebrew@gmail.com/) on May 05, 2013 13:59:05_

I've noticed in the test suite that clone-related tests will not pass if the test suite speed is set to a "loaw" value.

To reproduce, just run the clone.txt test as the first test of the suite, and it will fail.

Visually, it seems the clone card goes to the graveyard before being able to perform the actual copy.

_Original issue: http://code.google.com/p/wagic/issues/detail?id=952_

**Comment by kevlahnota** [comment]
Cannot reproduce this anymore.  Maybe this is fixed.
