### ISSUE TITLE
Exquisite blood + Sanguine bond infinite loop

### ISSUE THREAD

**Issue by xawotihs** [WagicProject/wagic#547]
_From [wagic.the.homebrew@gmail.com](https://code.google.com/u/wagic.the.homebrew@gmail.com/) on May 05, 2013 15:52:10_

#DESC: Sanguine Bond Whenever you gain life, target opponent loses that much life.
#DESC: Exquisite Blood: Whenever an opponent loses life, you gain that much life.

Having those 2 in game causes an infinite loop that never ends.
Previous attempts at fixing the issus have caused side effects and I reverted them ( see r4676 and r4692 )

Test:

[INIT]
firstmain
[PLAYER1]
inplay:Exquisite blood,Sanguine Bond
hand:Lightning bolt
manapool:{R}
[PLAYER2]
[DO]
Lightning bolt
p2
[ASSERT]
firstmain
[PLAYER1]
inplay:Exquisite blood,Sanguine Bond
graveyard:Lightning bolt
[PLAYER2]
life:0
[END]

_Original issue: http://code.google.com/p/wagic/issues/detail?id=953_

**Comment by kevlahnota** [comment]
The life check on trigger stops the loop unless the targetted player has cantlose condition.
