### ISSUE TITLE
unable to attack with copied angel

### ISSUE THREAD

**Issue by xawotihs** [WagicProject/wagic#549]
_From [mertensb...@gmail.com](https://code.google.com/u/116148808979954769334/) on June 04, 2013 18:06:28_

I'll do my best to describe all steps to reproduce this but it's pretty far into the game with many enchantments in place so it's a bit difficult to describe all relevant steps.
This is another example where being able to "dump" the game state would be really helpful. What steps will reproduce the problem? 1. A classic game against the deck "angelism"
2. AI has multiple "Moat" enchantments in play preventing creatures without flying to attack
3. AI has a "Sigil of the Empty Throne" in play creating 4/4 white angel creature tokens with flying
4. AI has multiple "Honor of the Pure" in play
5. I cast a Phantasmal Image copying one of those angel tokens which was a 7/7 angel creature, the reuslting creature has following subtypes: Angel - Creature - Illusion - Creature
6. When I cast a "Stingerfling Spider" that copied creature is highlighted as a potential target so at that state the creature is recognized as having "flying"
7. During my declare attackers phase I want to attack using that copy. What is the expected output? What do you see instead? I expect the selected creature to be declared as attacker instead nothing happens.

So either at this stage the flying attribute isn't recognized or the Moat is preventing all creatures to attack or Moat is preventing this copy to attack since it entered the game without flying. What version of the product are you using? On what operating system? Version 0.18.6 on android 4.1.1 Please provide any additional information below. at the start of each turn the abilities of Moat and Honor of the Pure trigger and are placed on the stack and resolve.
However Moat ability should be static IMHO and shouldn't trigger.
At the same time the "Feedback" (attached to one of the Moat enchantment)'s ability doesn't trigger.
Not sure if this is related or not.

Regards

Bram

_Original issue: http://code.google.com/p/wagic/issues/detail?id=956_

**Comment by zethfoxster** [comment]
This is summoning sickness, when you clone using aacloner it makes a exact copy, if the creature cloned had summoning sickness, so does the clone. Mtg rules.

Tried to reproduce, this was all i could figure out happened here.

Closing, open again if you run into a more narrowed down version of this, 

Have 30 cards in play and attack. Really doesnt help figure out what happened.
