### ISSUE TITLE
[alpha-195] deck editor grid layout fuzzy images

### ISSUE THREAD

**Issue by Rolzad73** [WagicProject/wagic#582]
While the grid layout deck editor looks good with the stock card visuals (as seen in the first image), when accessing an image pack for cards, the scaled down images are fuzzy.

It should be noted however that when a card is selected in the grid view, it appears clear.

It could also be seen a scaling artifact (or positioning artifact) in between the cards in the image packed version.

This test was performed on a Nexus 5 running stock Android 4.4

Standard grid editor:
![nexus_5-deckeditorgrid-standard_2013-12-08-11-49-39](https://f.cloud.github.com/assets/3611989/1700853/eb5ff1e2-6031-11e3-98cd-48d7622a7f9c.png)
Image packed grid editor:
![nexus_5-deckeditorgrid-imagepack_2013-12-08-12-41-42](https://f.cloud.github.com/assets/3611989/1700854/ed134606-6031-11e3-865a-13098a0083d6.png)

**Comment by zethfoxster** [comment]
This is psp ram limitations. Recent atempts to correct this have had destructive results.

It boils down to psp system only having 35mb of avilable ram. 

Note on psp vita, you can safely define huge cache as 500mbs, allowing for full hires gameplay.

My recommendation is 
Wagic requires psp vita or greater.
Anything else is legecy.
