### ISSUE TITLE
Emrakul isn't killed by creatures with deathtouch

### ISSUE THREAD

**Issue by mjnguyen** [WagicProject/wagic#597]
Playing a vampire deck versus the ai deck containing Emrakul I found this issue.  Using my vamp with deathtouch (Vampire Nighthawk) to block doesn't kill Emrakul.  From the text it seems like Emrakul should actually die since it has protection from colored spells.  Not sure if the current definition is correct but it seems like it.  however if deathtouch is put onto the stack then that might be the reason.  Not sure what the fix should be since the card defs isn't something I'm 100% familiar with.

**Comment by kevlahnota** [comment]
fixed on latest-master

**Comment by zethfoxster** [comment]
this is fixed
