### ISSUE TITLE
Android build process from wiki does not work quite right anymore

### ISSUE THREAD

**Issue by Rolzad73** [WagicProject/wagic#608]
As of commit c3583ade01ae3c76677bf97a0d683219cafa3f67, the Android build process as per the wiki fails on the ndk build step this message:
```
jni/../jni/../../../../JGE/src/SDLmain.cpp: In function '_jstring* Java_org_libsdl_app_SDLActivity_getResourceUrl(JNIEnv*, jclass)':
jni/../jni/../../../../JGE/src/SDLmain.cpp:94:31: error: 'WAGIC_RESOURCE_URL' was not declared in this scope
/cygdrive/d/SDK/android_ndk/build/core/build-binary.mk:269: recipe for target 'obj/local/armeabi/objs/main/__/__/__/__/JGE/src/SDLmain.o' failed
make: *** [obj/local/armeabi/objs/main/__/__/__/__/JGE/src/SDLmain.o] Error 1
```

Looking at the Travis CI build scripts shows that WAGIC_RESOURCE_URL is defined in the root mtg/build.xml but relies on an environment variable RELEASE_NAME to be created.

As well, $ant build.wagic.header is required to be run now to add these defines to projects/mtg/include/Wagic_Version.h

Although, the build.wagic.header task also adds this to the Wagic_Version.h:
```
#define WAGIC_VERSION_REVISION  ${env.TRAVIS_BUILD_NUMBER}
```
Which will probably not resolve in a user's personal dev env, but does not seem to break the build.

I have also observed that if WAGIC_RESOURCE_URL is not matched to a valid downloadable core resource, the application cannot start (which is to be expected).

**Comment by Rolzad73** [comment]
As seen in the screenshot below, if ${env.TRAVIS_BUILD_NUMBER} is not set, it refects in the app on the top version text, however, the game still works as normal:

![wagicverissue](https://cloud.githubusercontent.com/assets/3611989/8257107/612a328a-1679-11e5-88e4-dc9e852e051c.png)

**Comment by zethfoxster** [comment]
I cant compile a android build at all, what changed?

**Comment by Rolzad73** [comment]
> I cant compile a android build at all, what changed?

Its been a while since I looked at it, but there was effort so automate the build using Travis CI.  Which means it got switched over to use a travis script to build.  That might have broken the standalone compiling.

We should look into making it buildable standalone again, without breaking Travis.

@zethfoxster What was the method you used to build and the resulting error?

**Comment by kevlahnota** [comment]
@zethfoxster  When using ant to build (local android build), I think there is a missing folder/s, adding them will make the android build continue complete. I think it was objs folder or deps folder or both... It has something to do when compiling it stores the *.o or *.d files...

**Comment by zethfoxster** [comment]
That was exactly it. Thank you

**Comment by zethfoxster** [comment]
It was user error, becauei a moron oetimes.

**Comment by Rolzad73** [comment]
Tested the original wiki build to confirm and removed the workaround section that stated as such:

```
**NOTE:** as of commit [c3583ad](https://github.com/WagicProject/wagic/commit/c3583ade01ae3c76677bf97a0d683219cafa3f67), the ndk process fails because it cannot resolve "WAGIC_RESOURCE_NAME".  This build process has been updated with workarounds to alleviate that issue.  For explanation, refer to issue #[608](https://github.com/WagicProject/wagic/issues/608) 

##### Issue Workaround
1. Create required environment variable  
`$ export RELEASE_NAME=latest-master`

1. Update projects/mtg/include/Wagic_Version.h
   1. navigate to projects/mtg/ directory  
   1. In the terminal type:  
`$ ant build.wagic.header`
```
