### ISSUE TITLE
Xcode local builds failing

### ISSUE THREAD

**Issue by DeltaManiac** [WagicProject/wagic#610]
Trying to get Wagic running on mac with xcode 6+.
Builds are failing on the linking step
Steps
1. opened the wagic.xcodeproj in xcode
2. clicked the build button gor iphone 6 emulator
3. got error  :(

Did i miss any steps? ?

#Logs# 
Ld /Users/i077570/Library/Developer/Xcode/DerivedData/wagic-fvciqvmvljhpzjcjtgllhhfsddbm/Build/Products/Debug-iphonesimulator/wagic.app/wagic normal i386
    cd /Users/i077570/git/orginal/wagic/projects/mtg
    export IPHONEOS_DEPLOYMENT_TARGET=4.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk -L/Users/i077570/Library/Developer/Xcode/DerivedData/wagic-fvciqvmvljhpzjcjtgllhhfsddbm/Build/Products/Debug-iphonesimulator -L/Users/i077570/git/orginal/wagic/projects/mtg/../../admobsdk/iOS/GoogleAdMobAdsSDKiOS-5.0.5 -F/Users/i077570/Library/Developer/Xcode/DerivedData/wagic-fvciqvmvljhpzjcjtgllhhfsddbm/Build/Products/Debug-iphonesimulator -filelist /Users/i077570/Library/Developer/Xcode/DerivedData/wagic-fvciqvmvljhpzjcjtgllhhfsddbm/Build/Intermediates/wagic.build/Debug-iphonesimulator/wagic.build/Objects-normal/i386/wagic.LinkFileList -Xlinker -objc_abi_version -Xlinker 2 -Wl -fobjc-link-runtime -Xlinker -no_implicit_dylibs -mios-simulator-version-min=4.0 -framework CoreAudio -framework OpenAL -framework AudioToolbox -framework AVFoundation -weak-lstdc++ -weak_framework CFNetwork -weak_framework MobileCoreServices -weak-lc++abi -weak-lsqlite3 -weak_framework iAd -framework Foundation -framework UIKit -framework OpenGLES -framework QuartzCore -framework CoreGraphics -weak-lz -framework MessageUI -framework SystemConfiguration -framework CoreLocation -Xlinker -dependency_info -Xlinker /Users/i077570/Library/Developer/Xcode/DerivedData/wagic-fvciqvmvljhpzjcjtgllhhfsddbm/Build/Intermediates/wagic.build/Debug-iphonesimulator/wagic.build/Objects-normal/i386/wagic_dependency_info.dat -o /Users/i077570/Library/Developer/Xcode/DerivedData/wagic-fvciqvmvljhpzjcjtgllhhfsddbm/Build/Products/Debug-iphonesimulator/wagic.app/wagic

ld: -pie can only be used when targeting iOS 4.2 or later
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by DeltaManiac** [comment]
Ok
Browsing through the forums and travis I did come across some info that this project is built using qt. 
Will try using QT and post the results. 
Do confirm if i am right.

**Comment by xawotihs** [comment]
The iOS port is currently un-maintained and the Mac one is built using Qt. What's your interest ? both ?

**Comment by DeltaManiac** [comment]
Yes, both im just trying out a few stuff.  I just wanted to be able to debug the code and see what is happening.
Sadly qt is huge and currently downloading it.
Will update once i check with that. :)

**Comment by xawotihs** [comment]
https://github.com/WagicProject/wagic/blob/master/tools/macos.travis.yml is used by Travis to build the Macosx version automatically. You should be able to use Qtcreator and debug with wagic-qt.pro.

**Comment by xawotihs** [comment]
Should have been fixed on the master branch after the merge of the iOS-Build branch
