### ISSUE TITLE
Visual Studio 2013 Compatiblity

### ISSUE THREAD

**Issue by DeltaManiac** [WagicProject/wagic#611]
Is the current solution bundled with the project compatible with Visual Studio 2013 ? 
I opened the solution ( upgraded ) and tried running a build. Sadly it failed with error ? 

Am i missing some step to build the solution ? 

---------------
Error	12	error LNK2019: unresolved external symbol __ftoui3 referenced in function _SDL_HashDollar	C:\Work\wagic\JGE\Dependencies\SDL\VisualC\SDL\SDL_gesture.obj	SDL

Error	13	error LNK2019: unresolved external symbol __dtoui3 referenced in function _SDL_PrintFloat	C:\Work\wagic\JGE\Dependencies\SDL\VisualC\SDL\SDL_string.obj	SDL

Error	14	error LNK1120: 2 unresolved externals	C:\Work\wagic\JGE\Dependencies\lib\SDL.dll	1	1	SDL

Error	16	error C2678: binary '<<' : no operator found which takes a left-hand operand of type 'std::stringstream' (or there is no acceptable conversion)	c:\work\wagic\projects\mtg\src\testsuiteai.cpp	854	1	mtg

Error	15	error C2678: binary '<<' : no operator found which takes a left-hand operand of type 'std::ostream' (or there is no acceptable conversion)	c:\work\wagic\projects\mtg\src\gameobserver.cpp	1512	1	mtg

Error	3	error C2678: binary '!=' : no operator found which takes a left-hand operand of type 'zip_file_system::izfstream' (or there is no acceptable conversion)	c:\work\wagic\jge\src\jfilesystem.cpp	251	1	JGE

-----------------------------

**Comment by xawotihs** [comment]
On windows, the solution is built as non-regression test in the cloud using AppVeyor and projects/mtg/mtg_vs2010.sln without any issue.

**Comment by DeltaManiac** [comment]
Is the sln specific for a .Net framework ? 
I am trying to build it against 4.5.
Is it necessary to downgrade the version ?  If yes then approx which version? 

Thanks is advance 
Delta

**Comment by xawotihs** [comment]
It should not need .net framework at all. I used to build it with VS2010 without any issue.

**Comment by DeltaManiac** [comment]
Yep 
Got it up and running.
There are compiler issues while running with the new api's that are bundled with vs2013. 
Had to download 2010 and make it run.

Facing a problem while debugging though. During debug the program fails to load resources and causes a dump.
Will look into it and see what is the issue.

**Comment by zethfoxster** [comment]
"Facing a problem while debugging though. During debug the program fails to load resources and causes a dump.
Will look into it and see what is the issue."

this happens still in vs2015, had to copy my res folder a whole directory up for it to find it.
