### ISSUE TITLE
Something is wrong with AppVeyor

### ISSUE THREAD

**Issue by techtonik** [WagicProject/wagic#613]
It get built every 5 minutes for the same commit https://ci.appveyor.com/project/xawotihs/wagic/history

**Comment by xawotihs** [comment]
Yeah, I created a nice race condition in the cloud. It worked like that:
1) something was committed to github on the master branch
2) AppVeyor got notified that it needed to build
3) Build was OK, so an artifact was uploaded to github associated to a "latest-master" release
4) Github automatically creates a tag for each release
5) AppVeyor got notified that a new tag was added, so we go back to 2)

Fix was easy, now AppVeyor does not build on new tag.

**Comment by techtonik** [comment]
I wonder how much electricity is wasted by the mistakes in setups like that.. =)
