### ISSUE TITLE
Android is unusable now

### ISSUE THREAD

**Issue by theredbaron1834** [WagicProject/wagic#625]
I just noticed that github has current android builds, so I upgraded to the latest master. However, it is near unusable now, either because or an actual issue, or my incompetence / hidden options. I can see no way to play any spells that target. You tap mana, play the spell, but I cant find a way to target anything. You can't click anything while you hand is open, and closing your hand stops the spell.

Easy to reproduce. Get a fresh install, play a game with the default deck, and try and cast a spell.

**Comment by kevlahnota** [comment]
Can you try setting it with open hands? on the options?
here's a sample video:
http://vid44.photobucket.com/albums/f1/kevlahnota/20150919_0649051_zpsfo074ikg.mp4

**Comment by theredbaron1834** [comment]
Well, the back button doesn't work it seems. So I couldn't save the settings. I could not find a way to get it to work either, as I can't find out what the back button key code would be, so no editing the config.

However, I was able to check the setting on my pc, and copy over "closed_hand=visible" to my player options. It now works fine. Thanks.

**Comment by zethfoxster** [comment]
maybe consider making "closed_hand=visible" the default option.

**Comment by zethfoxster** [comment]
Andoid system is functioning, this is user preferences.
I just installed current release on 4 devices, all 4 are working including the one im typing this with.

Closing.
