### ISSUE TITLE
Typos in IVG _cards.dat:

### ISSUE THREAD

**Issue by Niegen** [WagicProject/wagic#662]
Typo in IVG _cards.dat:
primitve=Forest instead of primitive=Forest (missing an i)
Typo is repeated 4 times.

Also, a mountain is lacking its L rarity.

Finally, while I'm at it:
Angel of Salvation (EVT) is missing its rarity (R).
AEtherling (DGM) has an extra space after its rarity. Might cause trouble later on.

**Comment by kevlahnota** [comment]
Fixed #714
