### ISSUE TITLE
Nasty memleak crashing devices and its fix.

### ISSUE THREAD

**Issue by zethfoxster** [WagicProject/wagic#664]
Gameobserver.cpp at line 1159:
                SAFE_DELETE(original);				
		SAFE_DELETE(alternate);
	        SAFE_DELETE(buyback);
		SAFE_DELETE(flashback);
		SAFE_DELETE(retrace);
            }//end

safe_delete the other "new" cost created earlier. currently only original is being deleted. should read as i have it above. mem usage drops from a 100% upward climb into the gigs back down to a normal 132mb.

**Comment by kevlahnota** [comment]
The build failed on travis and appveyor but not because of this code. The automated build must be updated.

**Comment by xawotihs** [comment]
Fixed in 7a34543004e310342faade11befc4fac51715685.
