### ISSUE TITLE
super rare loop in ai combos and fix

### ISSUE THREAD

**Issue by zethfoxster** [WagicProject/wagic#667]
#HINT:combo hold(Glimmervoid|myhand)^until(artifact|mybattlefield)^cast(Glimmervoid|myhand)^totalmananeeded({0})

loop happens when ai sees this combo after drawing cards from another ability after he played a land for the turn.

ai gets stuck trying to play glimmervoid, but cant.

out of 300 games it triggered 2 times, which would have been 2 loops basically. rare, but better to fix then ignore it.

aiplayerbaka.cpp add line: 715

    if(!cost->getConvertedCost())
    {
		DebugTrace("AIPlayerBaka: Card was a land and ai cant play any more lands this turn.  ");
		if (target && target->isLand() && game->playRestrictions->canPutIntoZone(target, game->battlefield) == PlayRestriction::CANT_PLAY)
			return false;
        DebugTrace("AIPlayerBaka: Card or Ability was free to play.  ");
        if(!cost->hasX())//don't return true if it contains {x} but no cost, locks ai in a loop. ie oorchi hatchery cost {x}{x} to play.
            return true;
        //return true if cost does not contain "x" becuase we don't need to do anything with a cost of 0;
    }

**Comment by kevlahnota** [comment]
thanks zeth... why don't you message xawotihs to add you as a dev here...

**Comment by zethfoxster** [comment]
*wink* if he wanted to add me he would have already done so don't you think.

**Comment by xawotihs** [comment]
I'm not aware of you asking to join the project... anyway, invitation sent.

**Comment by zethfoxster** [comment]
thank you, not going to do major massive updates like i did before, mostly just bug fixing. trying to repro crashes and such and fix them as theyre the most annoying thing to me at the moment.
go to show someone wagic, looks terrible when it crashes infront of them, im sure everyone here can relate to this.
