### ISSUE TITLE
Flip cards and card rarity

### ISSUE THREAD

**Issue by zethfoxster** [WagicProject/wagic#675]
We need a way to list flip cards so that thier flipped versions dont show up in shop as cards you can purchase, card rarity=flip?

**Comment by kevlahnota** [comment]
Rarity=f should be fine I guess.

**Comment by kevlahnota** [comment]
the flipped cards have rarity=t, I guess we can filter out all rarity =t so it will not display on the shop

**Comment by zethfoxster** [comment]
They should get thier own which can be used for all cases of flip like kami and innastrad. Rarity=F was a good suggestion, only on thier 2nd halfs.

**Comment by zethfoxster** [comment]
Postby sandman423 » Sat Jul 30, 2016 3:24 pm

::Bug Report::

-I was playing Momir and got a Stormtide Leviathan and I have 3 flyers and him but he can't attack nor can my flyers. It does make all lands Islands in addition I believe because when I try and click lands I get the option to tap for blue.

-Also with Always Watching on the field my flip cards don't get +1/+1 but they gain Vigilance. I think the game thinks that flipped cards are tokens.

**Comment by zethfoxster** [comment]
exactly why i said they shouldnt be rarity=t....make them rarity F and filter them out of the shop by F

**Comment by kevlahnota** [comment]
the code for flip doesn't copy their flipped counterpart rarity, even my SOI sets lambholt butcher rarity is token. Also we have an  indicator if its token.
[card]
primitive=Lambholt Butcher
id=409977
rarity=T
[/card]
[card]
primitive=Lambholt Pacifist
id=409976
rarity=U
[/card]

but when you try ingame Always Watching works on transformed cards. Here's a screenshot:
![sample2](https://cloud.githubusercontent.com/assets/9781539/17273721/2a1dc486-56f2-11e6-860d-d4cda7f3262c.jpg)

So  we don't know which "Flip/Transform" cards Always Watching doesn't affect.

**Comment by kevlahnota** [comment]
all card tokens and cards with negative id cannot be bought anymore.
there's an option to show them in general settings, but you cannot add them anymore in your deck.
