### ISSUE TITLE
Lands don't appear in the deck editor

### ISSUE THREAD

**Issue by kevlahnota** [WagicProject/wagic#682]
But if you add this in CardPrimitive.cpp line: 430

>     case Constants::MTG_COLOR_WASTE:
>         value = kColorBitMask_Land;
>         break;

they will reappear in the deck editor. weird...

**Comment by zethfoxster** [comment]
The {c} is using lands quad color and mana icon, it has to do with the way the color quads are loaded.

**Comment by zethfoxster** [comment]
Create a quad for colorless, name it waste and place it in graphics folder, see if that corrects the issue

**Comment by zethfoxster** [comment]
no point in making a quad, the above is a fair enough fix for it. colorless is artifact, we just occupy the kbitmask of land which was unused for anything other than deck sort. so this is more than fine until MTG introduces a REAL new color.
