### ISSUE TITLE
gravelgill duo and cantattack

### ISSUE THREAD

**Issue by zethfoxster** [WagicProject/wagic#691]
lord(creature|opponentbattlefield) cantattack

ai using gravelgill duo can still attack with it. AI deck air sea battle.

**Comment by zethfoxster** [comment]
the rest of the 15 creatures couldnt attack i should mention, ONLY gravegill, and every game.

**Comment by kevlahnota** [comment]
Can you confirm on current build if this is still an issue?

**Comment by zethfoxster** [comment]
its cleared away. wonder what caused it when I first made this.
