### ISSUE TITLE
forks to be responsible for passing commits however

### ISSUE THREAD

**Issue by zethfoxster** [WagicProject/wagic#718]
The command "tools/travis-script.sh" exited with 1.

all builds always fail and im being told its a file in master branch thats being told to run in forks. can we manage this file better so that our "passing" forks are actually passing and not "oh if it fails and you passed test you didnt fail"

cause to me the big red letters at the top tell me my build fails.

**Comment by kevlahnota** [comment]
maybe it has to do with tokens/credentials since inside it calls other script
./tools/build-macos-script.sh

**Comment by xawotihs** [comment]
The problem is not really the exit 1, it's the fact that pull requests are not built for osx and ios... I think it will be fixed as soon as we use the same matrix build on the master branch as I use in the cmake branch.

**Comment by zethfoxster** [comment]
Going to close this, this is an issue with forks vs main and how travis handles them, im sure there is a way i can fork wagic as an exact duplicate picking up whatever file controls this. But it boils down to user error, not something in codebase.
