### ISSUE TITLE
Enters the battlefield tapped triggered event 

### ISSUE THREAD

**Issue by kevlahnota** [WagicProject/wagic#728]
I think wagic is missing the "enters the battlefield tapped".
sample test:

> [INIT]
> firstmain
> [PLAYER1]
> hand:Stomping Ground, Temple Garden
> inplay:Exploration
> [PLAYER2]
> inplay:Lifetap
> life:20
> [DO]
> Stomping Ground
> choice 1
> Temple Garden
> choice 1
> [ASSERT]
> firstmain
> [PLAYER1]
> inplay:Exploration, Stomping Ground, Temple Garden
> [PLAYER2]
> life:20
> [END]

player 2 must not gain life since in this test, player 1 chooses not to "untap" those two shocklands. but their current code has auto=tap, so it will trigger cards like Lifetap. If possible abilities=autotap to prevent trigger? I think also enters the battlefield untapped so no triggered event for untap when the player chooses to pay 2 life for it...

![Lifetap](http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=2164&type=card) ![Stomping Ground](http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=405110&type=card)

**Comment by zethfoxster** [comment]
You mean have it come in play already tapped, instead of tapping after being put in play?

**Comment by kevlahnota** [comment]
Yes, Entering the battlefield tapped is not interpreted as "entering the battlefield and then getting tapped". Because its already "tapped"

**Comment by kevlahnota** [comment]
Just found it:

603.2d Some trigger events use the word “becomes” (for example, “becomes attached” or “becomes blocked”). These trigger only at the time the named event happens—they don’t trigger if that state already exists or retrigger if it persists. An ability that triggers when a permanent “becomes tapped” or “becomes untapped” doesn’t trigger if the permanent enters the battlefield in that state. #

Example: An ability that triggers when a permanent “becomes tapped” triggers only when the status of a permanent that’s already on the battlefield changes from untapped to tapped.

**Comment by kevlahnota** [comment]
Fixed #730
