### ISSUE TITLE
Unhandled exception in debug mode

### ISSUE THREAD

**Issue by kevlahnota** [WagicProject/wagic#733]
to replicate: run in debug mode (attach process to wagic.exe)
then cast control magic to a creature an opponent controls.

**Comment by kevlahnota** [comment]
I think it has something to do when a card "moves" from zone because I tried casting AEther Mutation and the unhandled exception occurs in debug mode.

**Comment by zethfoxster** [comment]
Ill check it when i get home.

**Comment by zethfoxster** [comment]
ok so i can not reproduce this, can you get us some more info on this?
normally when debugging it tells you exactly where the crash happened.

**Comment by kevlahnota** [comment]
I think I found my problem, I was testing some card and I have this code on a card:
autohand={0}:name(Control Magic) activate castcard(normal named!:Control Magic:!)

then when I activate it, the generated Control Magic seems crashing after targetting a creature...

**Comment by kevlahnota** [comment]
it was pointing mtggamezones.cpp line 992   ->      return p->game->inPlay;
when I check it p is invalid

**Comment by zethfoxster** [comment]
ill look into it tomarrow morning. :)

**Comment by zethfoxster** [comment]
its not moves that has the issue, its most likely in the cast card code named!: is most likely not setting the controller or reciever correctly.

**Comment by zethfoxster** [comment]
are you still getting this? if not can you close this issue, thanks kev

**Comment by zethfoxster** [comment]
found it and it was in castcard, however fixing it at initZone,

**Comment by zethfoxster** [comment]
can you confirm and close this with the fix i added.

**Comment by kevlahnota** [comment]
Yes this is fixed. Thank you
