### ISSUE TITLE
Phasealter & Nextphasealter doesn't work on instants and sorceries

### ISSUE THREAD

**Issue by kevlahnota** [WagicProject/wagic#734]
Try casting Savor the Moment, you get your additional turn but the untap is not skipped.
![Savor the Moment](http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=159404&type=card)

Also try casting Seize the Day, you wont get additional combat phase
![Seize the Day](http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=30573&type=card)

**Comment by zethfoxster** [comment]
It does work on perminents tho?

**Comment by zethfoxster** [comment]
please check your repro, I tested this and both cards work with no issues at all. I checked the other bug and had no crash or exception either. try doing a "clean" and see if it improves, or see if there is something changed in your repro compared to master.

**Comment by zethfoxster** [comment]
Seize the Day is however missing the "untap" in it. that is something i noticed.

**Comment by kevlahnota** [comment]
here's a sample test:

> #NAME: Savor the Moment
> #the next untap must be skipped so i cant tap the 2 lands
> [INIT]
> combatattackers
> [PLAYER1]
> inplay:Juggernaut, Island, Mountain, Silver Myr
> hand:Savor the Moment
> [PLAYER2]
> inplay:Wall of Stone
> [DO]
> Juggernaut
> next
> Wall of Stone
> next
> next
> next
> Island
> Mountain
> Silver Myr
> Savor the Moment
> Eot
> next
> Island
> Mountain
> [ASSERT]
> upkeep
> [PLAYER1]
> inplay:Juggernaut, Island, Mountain, Silver Myr
> graveyard:Savor the Moment
> [PLAYER2]
> inplay:Wall of Stone
> life:15
> [END]

**Comment by zethfoxster** [comment]
this should be fixed in my fork, i think i pushed it already, can you varify?

**Comment by kevlahnota** [comment]
Yes, It works ok now, I tried your fix on your fork :)
