### ISSUE TITLE
Adding Arlinn Kord causes crash

### ISSUE THREAD

**Issue by GPBurdell06** [WagicProject/wagic#879]
Adding Arlinn Kord to a deck causes the application to crash.  When you are in collection view, add Arlinn to the deck.  Then switch to deck view and it crashes on me.  I have verified this bug against the latest release.

**Comment by kevlahnota** [comment]
it's a typo when parsing the name, try this code:
```
[card]
name=Arlinn Kord
auto=counter(0/0,3,loyalty)
auto={C(0/0,1,Loyalty)}:name(+1: loyalty) donothing restriction{compare(cantargetcre)~lessthan~1}
auto={C(0/0,1,Loyalty)}:name(+1: 2/2 creature) target(creature) 2/2 ueot
auto={C(0/0,0,Loyalty)}:name(0: wolf token) token(Wolf,creature Wolf,2/2,green) && flip(Arlinn, Embraced by the Moon)
text=+1: Until end of turn, up to one target creature gets +2/+2 and gains vigilance and haste. -- 0: Put a 2/2 green Wolf creature token onto the battlefield. Transform Arlinn Kord.
mana={2}{R}{G}
type=Planeswalker
subtype=Arlinn
[/card]
```
please report if you crash using these...

**Comment by kevlahnota** [comment]
do you still have issues with arlinn kord with the latest-release?

**Comment by GPBurdell06** [comment]
No issues in the latest release.  It works both putting her into the deck and playing her too.

BTW is there a way to see a change log and what got added in the latest releases?

**Comment by kevlahnota** [comment]
Im closing this since its already fixed. The changelog.md is not updated but if you want to see all the changes from commits here: https://github.com/WagicProject/wagic/commits/master
