### ISSUE TITLE
Can't download normal version, SVN crashes on startup (WIN)

### ISSUE THREAD

**Issue by LethalPigeon7** [WagicProject/wagic#925]
This is my first contact with the software. WIN 7 SP 1  
[probably useless screenshots](http://imgur.com/a/XsM3u)

**Comment by kevlahnota** [comment]
Google code is closed that's why the project moved to github. Try downloading the latest master here from the release...  https://github.com/WagicProject/wagic/releases

**Comment by Rolzad73** [comment]
@kevlahnota @LethalPigeon7 Although the Window build isn't showing up again (comes from AppVeyor).  I guess that should be looked at again.
