### ISSUE TITLE
Travis CI changes have left Android update.android.manifest ant call broken

### ISSUE THREAD

**Issue by Rolzad73** [WagicProject/wagic#980]
Because of a series of dependancies deprecations, the update.android.manifest ant call no longer works.

1. It began with the Ant version updating on Travis CI to 1.9.3 (it was 1.8.2).
1. That meant that Java 7 was no longer required to match Ant 1.8.2 (as well, Java 7 installer is no longer available).
1. Because of that, the groovy task now complains about java.lang.NoClassDefFoundError: [Ljava/util/HashMap$Entry; as something moved in Java 8.

I am no expert in ant, or groovy tasks, so I do not know how to fix it.  Following is the line I commented out so that it can be tackled later if need be.

https://github.com/WagicProject/wagic/commit/363383df6d9e2731add17e7916809269602c1f26#diff-961001fddaa8e2a4984a9f2082a4dc57R47

**Comment by Vitty85** [comment]
Since the 0.21.0 version, the Android app is again building on Travis CI, i'm gonna close this issue..
