### ISSUE TITLE
Windows 10 Wagic won't even open

### ISSUE THREAD

**Issue by Xirious** [WagicProject/wagic#981]
Windows 10
i7 7700k
1080ti
SSD installation but tested on multiple hard drives too.

App still refuses to open. Tried on two different PCs, both with different hardware, Win 10 at different versions.

This is a persistent problem. I was told it has something to do with my PC with the last version. I expect it to be a similar reply this time.

**Comment by Ryan1729** [comment]
Was it popping up error boxes like this?

![MSVCR100](https://user-images.githubusercontent.com/2133026/63322270-3dfd8b00-c2e0-11e9-9dfe-4c8fef2d50fb.png)

I fixed that problem by installing `vcredist_x86.exe` from [this microsoft.com page](https://www.microsoft.com/en-us/download/details.aspx?id=26999) and then restarting the computer. It will not work if you do not restart the computer.
