### ISSUE TITLE
Compiling Wagic: Unhandled Exception: access violation writing location error

### ISSUE THREAD

**Issue by JLYNCH5** [WagicProject/wagic#983]
When Compiling the code using visual studio express v2010 I get a handling exception error. From the compiling source code doc Wiki it states errors are normal, but doesn't discuss which errors. 

However,  these errors are keeping me from compiling even after I press the green play button again "Debug" method. 

 "Sometimes the program tries to build JGE and Wagic in the wrong order, but it will then work on the second attempt."  

I think this is happening, but it does not work on the second attempt  I'm using a Windows 10 Machine.  I right-click on the solution mtg_vs2010 and do a clean build (everything is good there).  Then I do a build of MTG project and click on debug (play button)  it tries compiling but I get an unhandled exception: access violation writing location error posted in screenshot below. 

Any help or updated method of compiling would be much appreciated.  Thank you - Jeff
 
![IMG_20190603_160850](https://user-images.githubusercontent.com/50506714/58838560-4bc63d00-861c-11e9-8c9d-6a9e3a0e1d37.jpg)
  

VS2010 found here:
https://filehippo.com/download_visualc_2010_express_edition/

**Comment by JLYNCH5** [comment]
![image](https://user-images.githubusercontent.com/50506714/61165302-eb100700-a4db-11e9-81f3-b81ec43fe36a.png)

**Comment by JLYNCH5** [comment]
![image](https://user-images.githubusercontent.com/50506714/61165313-0418b800-a4dc-11e9-8381-f7c9dfb2467f.png)

**Comment by JLYNCH5** [comment]
Also here's this:  

Microsoft Visual C++ 2010 Express Key: 
6VPJ7-H3CXH-HBTPT-X4T74-3YVY7

**Comment by JLYNCH5** [comment]
This looks like a font issue any help in getting the how to compile doc updated.

**Comment by JLYNCH5** [comment]
WFont * mFont = WResourceManager::Instance()->GetWFont(Fonts::MENU_FONT);

**Comment by JLYNCH5** [comment]
Is causing the issue I believe

**Comment by JLYNCH5** [comment]
![image](https://user-images.githubusercontent.com/50506714/61165585-c158df00-a4df-11e9-91ce-a69a89b749bf.png)

**Comment by JLYNCH5** [comment]
![image](https://user-images.githubusercontent.com/50506714/61165612-efd6ba00-a4df-11e9-9094-6b9c87ad8ec2.png)

**Comment by JLYNCH5** [comment]
![image](https://user-images.githubusercontent.com/50506714/61165983-cec49800-a4e4-11e9-8d30-0c3eb945dd1a.png)

**Comment by JLYNCH5** [comment]
Thank you  EduardoMunozGomez, my sincerest apologies to you as well.  I just saw your comment.  I know you posted the day I opened this issue, but I was unable to see your comment for several months.  I'm not sure why but I was looking almost hourly for a reply and I never saw it until now.  That's why I kept posting screenshots.  It's probably a user error on my end a setting is off or something; so I do apologize.    

Yes! :-)   your link helped me a lot.  I am error free now,  I used this method, " the working directory isn't automatically the one where the executable is located. To fix this, right-click on mtg in your solution explorer, choose properties, and under Configuration Properties - Debugging, set the 'Working Dir' value to "$(TargetDir)"."  and it compiled no problem.

EduardoMunozGomez,  I really appreciate you taking the time to post that link.  I look forward to learning a lot about Wagic and being apart of the Wagic community.  Thank you very much, If you need too,  you can close this issue; it's resolved.

**Comment by EduardoMunozGomez** [comment]
My profile was shadowbanned, my account was flagged but I was never
notified.

No explanation was given.

I just noticed it recently AND github support cleared my account from any
flags.
