### ISSUE TITLE
Is Android version still supported?

### ISSUE THREAD

**Issue by dnp87** [WagicProject/wagic#984]
Hello. Is Android version officially supported at the moment?
Since last release happened not long ago, there's no android version it it and official Wagic forum seems to be dead, I figured it would be the best place to ask.

**Comment by aknight2015** [comment]
I'd also like to know. I originallly played it on PSP.

**Comment by Vitty85** [comment]
Hi,

On my fork project i compiled a new release for Android: https://github.com/Vitty85/wagic/releases/tag/wagic-v0.21.1

You can also take a look here for PSP and images:
http://wololo.net/forum/viewtopic.php?f=17&t=66595&start=20#p99279

**Comment by dnp87** [comment]
@Vitty85, I saw it at the forum. Good job ressurecting it!
