### ISSUE TITLE
No hand

### ISSUE THREAD

**Issue by benshurts** [WagicProject/wagic#993]
On pc when I go into a game I don't draw any cards and have no hand.

**Comment by Vitty85** [comment]
It works fine for me. Try to unzip the content of core and user the directrory Res uncompressed.

**Comment by zie87** [comment]
On default a closed hand is invisible. Can you try to press 'A' in the game or change the options to show your hand?

**Comment by lamelizard** [comment]
I had the same issue, I can confirm that changing it in the options helped. (Pressing 'E' worked too, I don't know if my keybindings are the default ('A' is bound to Left)).
